### ISSUE TITLE
Markdown heading sizes don't work?

### ISSUE THREAD

**Issue by GideonWolfe** [panr/hugo-theme-terminal#109]
I'm not sure if this is on purpose but it's a bit frustrating. 

Usually the more `#`s you add, the smaller the heading gets. 

# Heading 1
### Heading 3

This is not the case on my site. I try to organize my page with headings and subheadings to break down topics, but all headings appear the same size to me.

**Comment by panr** [comment]
Yes, it doesn't work like you expect, because I reset all heading styles. I'm gonna make a fix for this tomorrow 👌

**Comment by GideonWolfe** [comment]
That's great to hear!

**Comment by panr** [comment]
@GideonWolfe all done 😎 https://github.com/panr/hugo-theme-terminal/commit/7ac0deff8728bca927f180f06a20c36697d8356e

Now you can set `oneHeadingSize = false` in config file to set headings to their default size.

**Comment by GideonWolfe** [comment]
Awesome!
