### ISSUE TITLE
Feature request: Bullet styling!

### ISSUE THREAD

**Issue by miphilomath** [panr/hugo-theme-terminal#11]
If possible, can we add the bullet styling in this theme? 

Triangular bullets, look like something I want to expand to read some hidden content.

**Comment by panr** [comment]
@miphilomath You can add `static/style.css` with additional styling ;-)

```
ul {
  list-style: [any matching rule];

  li {
    &:before {
      display: none;
    }
  }
}
```
or 

```
ul {
  li {
    &:before {
      content: [any working sign you want];
    }
  }
}
```
