### ISSUE TITLE
Background color of code block

### ISSUE THREAD

**Issue by GideonWolfe** [panr/hugo-theme-terminal#110]
Did this change in the last update?

![DeepinScreenshot_select-area_20200105122501](https://user-images.githubusercontent.com/32942052/71785611-6ac3ed80-2fb6-11ea-9457-88e8bda5bb01.png)
It looked nice when it was a clear background which worked great with the color theme. Now it's kind of a sickly green that doesn't really fit the pallet.

**Comment by panr** [comment]
I’ve seen it today. Don’t know why this broke, but I’ll fix it soon 😬

**Comment by panr** [comment]
Fixed. I also changed overall styling and added border around code blocks for better readability ;-)

<img width="844" alt="image" src="https://user-images.githubusercontent.com/1303365/71805861-9ce15800-3067-11ea-8fda-9c2649a24e21.png">

**Comment by GideonWolfe** [comment]
This looks *extremely* slick. :clap: :clap: I *hate* to be this guy but I noticed another small thing that usually only happens when I run the server locally but I haven't seen in prod until now.

![DeepinScreenshot_select-area_20200106104853](https://user-images.githubusercontent.com/32942052/71840529-58a78500-3072-11ea-9670-9dcd4fb2959f.png)

As you can see in the top bar I have three links enabled before it goes into dropdown overflow menu. I couldn't find a manual way to choose the order, so I capitalized the links I wanted to be separate from the dropdown. This should be `Projects`, `Contents`, and `About`.

This usually works fine, but sometimes as you can see in the picture it will be randomly not in order.

**Comment by panr** [comment]
Hmm... `weight` param doesn’t work in menu config? 🤔

**Comment by GideonWolfe** [comment]
Nice, that seemed to have done the trick! Not sure why it randomly broke but it's all good now :+1:

**Comment by panr** [comment]
🎉
