### ISSUE TITLE
PrismJS: line numbering alignment issue

### ISSUE THREAD

**Issue by knightjoel** [panr/hugo-theme-terminal#112]
While working on a partial for #26, I discovered a weird alignment issue when activating PrismJS line numbers. The numbers are slightly misaligned vertically from the actual text such that in long blocks of code, the line numbers are completely misaligned. This also affects line highlighting. 

I'm struggling to see what the actual cause is and no amount of fooling with the CSS for either the line-number `<span>` or the `<code>` block has gotten me any closer.

I've reproduced the issue [here](http://hugo-terminal.s3-website-us-west-2.amazonaws.com/one/). This is generated with Terminal @ 4823366 using only the CSS included with Terminal (nothing in the local static directory).

Is anyone else able to spot root cause?

**Comment by knightjoel** [comment]
More data points:

- I can reproduce the issue in Firefox 72 on Win 10
- I cannot repro in Chrome 79 on Win 10
- I cannot repro in Safari on iOS 13
- I cannot repro in Firefox 72 on Ubuntu

When rendering my test case in Firefox's [quirks mode](https://developer.mozilla.org/en-US/docs/Web/HTML/Quirks_Mode_and_Standards_Mode) on Win 10, everything looks fine. So it seems this is somehow related to Firefox, possibly only on Win 10. This does not seem to be related to Terminal at all.

**Comment by sophiabrandt** [comment]
I merged your commit into my personal fork of the theme, and I think the error also occurs. See [here](https://www.rockyourcode.com/how-to-start-and-restore-tmux-sessions-automatically-with-tmux-continuum/#linux).
Chromium 79.0.3945.117 on Manjaro Linux 4.19.96 x86_64

**Comment by knightjoel** [comment]
And yet in Safari on iOS 13, the highlight is perfect on line 6.

I've been unable to root cause this so I've moved to Hugo's built-in
highlighting and syntax coloring for now.

**Comment by panr** [comment]
Hi @knightjoel, just fixed line-numbers and highlight styling, so those should work fine now :-)
I quickly tested the changes with your shortcode for prismjs, but I'll probably do a code review of your PR tomorrow 😎

**Comment by knightjoel** [comment]
Hey @panr, I've pulled 2bb3d3d and updated my [test site](http://hugo-terminal.s3-website-us-west-2.amazonaws.com/one/) but I still see the same behavior. This screenshot from FF 72 on macOS.

<img width="323" alt="Screen Shot 2020-01-20 at 20 50 23" src="https://user-images.githubusercontent.com/17298529/72774099-a2da4b80-3bc6-11ea-9fbe-2790121fd5b5.png">

**Comment by panr** [comment]
![confused](https://user-images.githubusercontent.com/1303365/72783735-6ee34280-3c27-11ea-9eb0-6f37b850b1cd.gif)

I'll give it another try today...

**Comment by panr** [comment]
Should be finally fixed here: https://github.com/panr/hugo-theme-terminal/commit/2fcbefa09f1209fe1b4739a2897b263662664e3e

**Firefox:**
<img width="583" alt="image" src="https://user-images.githubusercontent.com/1303365/72784387-0301d980-3c29-11ea-870b-c943081fd590.png">

**Safari:**
<img width="620" alt="image" src="https://user-images.githubusercontent.com/1303365/72784420-10b75f00-3c29-11ea-9499-9f13cdc446a1.png">

**Edge (Chromium):**
<img width="646" alt="image" src="https://user-images.githubusercontent.com/1303365/72784454-26c51f80-3c29-11ea-917d-21e4287d4352.png">

**Comment by knightjoel** [comment]
Looks good to me too. Nice spot.

Would you mind committing an updated static/assets/style.css ?



.oel

**Comment by panr** [comment]
Oh, right... Don't know why it hasn't been pushed 🤔

**Comment by panr** [comment]
It's up https://github.com/panr/hugo-theme-terminal/commit/20ce0633979a301f3f47d47a3270c959924e97e0. Sorry about that 😬

**Comment by knightjoel** [comment]
Thanks Radek!

**Comment by willstocks** [comment]
Is there a correct/supported method of line numbering/highlighting rather than via manually inputting the correct HTML markup?

**Comment by knightjoel** [comment]
This whole issue is about not having the manually write HTML markup for highlighting :) See #113 for a commit that enables this.
