### ISSUE TITLE
_index.md not picked up by theme

### ISSUE THREAD

**Issue by fboerman** [panr/hugo-theme-terminal#13]
Hi,

I love the look of your theme but ran into a simple problem. for folder structure I would like my posts to setup in a way that I have a folder per post and a _index.md file which contains the post itself as explained here: https://gohugo.io/content-management/organization/ under content organization.

However when I do this posts do not show up in the menu and if I manually go the their url it displays a blank page (but not a 404). How do I get this working with this theme?

**Comment by panr** [comment]
As far I understand, what you want to do is to have `index.md` inside each folder, not `_index.md` which is necessary to have a nested file (url) structure.
