### ISSUE TITLE
Failed build on server due to merge commit #128

### ISSUE THREAD

**Issue by brotherlymite** [panr/hugo-theme-terminal#138]
The previous code in `partials/head.html` is causing a failed build on the server.
I tried it on both `netlify` and `zeit` but is causing a failed on both however it was working absolutely fine on both `hugo server` and when building it from the terminal using the command `hugo`.

I replaced the code 
```
{{ if and (ne .IsHome) (isset .Params "cover") }}
  <meta property="og:image" content="{{ .Param "cover" | absURL }}">
{{ else }}
  {{ if isset $.Site.Params "favicon" }}
    <meta property="og:image" content="{{ $.Site.Params.favicon | absURL }}">
  {{ else }}
    <meta property="og:image" content="{{ printf "img/favicon/%s.png" $.Site.Params.ThemeColor | absURL }}">
  {{ end }}
{{ end }}
```
with
`<meta property="og:image" content="{{ if .IsHome }}{{ $.Site.Params.favicon | absURL }}{{else}}{{ .Params.Cover | absURL }}{{ end }}">`

and now it builds totally fine on the server.

**Comment by panr** [comment]
@brotherlymite do you have any error msg?

Also, can you try this:

```
{{ if and (not .IsHome) (isset .Params "cover") }}
  <meta property="og:image" content="{{ .Param "cover" | absURL }}">
{{ else }}
  {{ if isset $.Site.Params "favicon" }}
    <meta property="og:image" content="{{ $.Site.Params.favicon | absURL }}">
  {{ else }}
    <meta property="og:image" content="{{ printf "img/favicon/%s.png" $.Site.Params.ThemeColor | absURL }}">
  {{ end }}
{{ end }}
```

**Comment by bowlinearl** [comment]
Here's the error.

`Building sites … ERROR 2020/04/16 15:37:45 render of "home" failed: execute of template failed: template: _default/list.html:7:5: executing "_default/list.html" at <partial "head.html" .>: error calling partial: ".../themes/terminal/layouts/partials/head.html:43:11": execute of template failed: template: partials/head.html:43:11: executing "partials/head.html" at <ne>: wrong number of args for ne: want 2 got 1`

**Comment by panr** [comment]
OK, so as I thought... Could someone test if changing `ne` to `not` in:

```suggestion
{{ if and (not .IsHome) (isset .Params "cover") }}
```

fixes the issue?

**Comment by brotherlymite** [comment]
Yes I've tested it and now it builds perfectly on the server also I've send a PR for the same.
Thanks
