### ISSUE TITLE
custom color adding

### ISSUE THREAD

**Issue by fboerman** [panr/hugo-theme-terminal#14]
Hi,

I love the look of your theme in terms of layout fonts etc but I was thinking about experimenting with a custom color. Would that be possible with this theme?

**Comment by panr** [comment]
Hi, you can easily add `static/style.css` with:

```
:root {
  --accent: [your color];
}
```

**Comment by hum6ug** [comment]
This is working as expected. But how to change the background-color as-well?

```--background-color``` or ```--background``` is not working

**Comment by panr** [comment]
Unfortunately, background color is generated by static `color-mod()` function (to blend dark background with accent color) while css files are compiling. That's why I have 4 different (also static) themes depends on config...

**Comment by hum6ug** [comment]
Well, ok. But there is another thing. When I choose orange as my themeColor but then use the accent #a7d129 the <div class="post-meta"> color will still be orange

**Comment by panr** [comment]
How do you pass accent variable? You can add `static/style.css` with:

```
:root {
  --accent: [your color];
}
```

or change variable inside theme and then recompile it using `yarn build` from `theme/terminal` directory.

**Comment by hum6ug** [comment]
That's my ```static/style.css```:
```
:root {
  --accent: #3e64a3;
}
```
And that's the result:

![2019-06-06-09-36-05_632x416_grim](https://user-images.githubusercontent.com/9086371/59015235-cec6dd80-883e-11e9-9937-3ffb6ab6bbd1.png)

Also the generated favicon stays the same (orange). Maybe it is possible to change it to the accent

**Comment by acodercat** [comment]
> Hi, you can easily add `static/style.css` with:
> 
> ```
> :root {
>   --accent: [your color];
> }
> ```

Hi, It doesn't work for me!
