### ISSUE TITLE
Help needed.

### ISSUE THREAD

**Issue by Hime0698** [panr/hugo-theme-terminal#145]
Hi, this might not be the right place to post this but I cant think of a better one so here goes.

I am trying to make one of the top links on the page e.g the about button simply link to a file.

In this case repurposing one of the buttons to say Resume and have clicking it download the pdf of my resume.

I cant for the life of me figure out how to do this..... Could anyone weigh in?

**Comment by FizzyGalacticus** [comment]
@Hime0698 if you run `hugo new about/index.md` and create an entry in the `languages.<language_code>.menu.main` for `about`, it should work. Check out my [config](https://github.com/FizzyGalacticus/fizzygalacticus.github.io/blob/master/src/config.json#L39-L41) and my [about page](https://github.com/FizzyGalacticus/fizzygalacticus.github.io/blob/master/src/content/about/index.md) it should lead you in the proper direction.

**Comment by panr** [comment]
@Hime0698 you can also do just:

```
[languages.en.menu]
      [[languages.en.menu.main]]
        identifier = "resume"
        name = "Resume"
        url = "https://link-to-your-resume.com/docs/resume.pdf"
```
