### ISSUE TITLE
Tags + categories pages not listing anything

### ISSUE THREAD

**Issue by FizzyGalacticus** [panr/hugo-theme-terminal#151]
I'm still new to Hugo, and trying to understand the load orders.

I've noticed that nothing appears on `/tags` or `/categories` pages other than the initial header. I'm wondering if this is something on my part, or if it's actually a bug/feature? I notice that the pages in the USERS.md file also do not show content on these pages.

I would also be happy to help fix this issue if pointed in the right direction.

Thanks!

**Comment by panr** [comment]
It's a bug ;-( I didn't provide a index file for that content 😬

**Comment by panr** [comment]
@FizzyGalacticus it should work now ;-)
