### ISSUE TITLE
"Failed to render pages" when migrating from other theme

### ISSUE THREAD

**Issue by johnassel** [panr/hugo-theme-terminal#152]
Hi,
I'm trying to migrate to the terminal theme coming from terminal.386.
I cloned the repo into /themes and used the sample config provided.
When executing "hugo -D" it gives me this:
`Building sites … ERROR 2020/06/10 11:38:48 render of "page" failed: execute of template failed: template: _default/single.html:7:5: executing "_default/single.html" at <partial "head.html" .>: error calling partial: "/var/www/blog/build/themes/hugo-theme-terminal/layouts/partials/head.html:54:16": execute of template failed: template: partials/head.html:54:16: executing "partials/head.html" at <.Params.categories>: range can't iterate over intern
Total in 32 ms
Error: Error building site: failed to render pages: render of "page" failed: execute of template failed: template: _default/single.html:7:5: executing "_default/single.html" at <partial "head.html" .>: error calling partial: "/var/www/blog/build/themes/hugo-theme-terminal/layouts/partials/head.html:54:16": execute of template failed: template: partials/head.html:54:16: executing "partials/head.html" at <.Params.categories>: range can't iterate over intern`

Any idea what I'm missing or what is going wrong here?
Thanks!

**Comment by johnassel** [comment]
Ah, the problem was indeed the taxonomies:
I declared them in one article with `categories: "intern"`.
Changing it to `categories: ["intern"`] made it work!

Thank you!

**Comment by panr** [comment]
No problem. Glad it works 🎉
