### ISSUE TITLE
How to enable Fira Code ligature?

### ISSUE THREAD

**Issue by srevinsaju** [panr/hugo-theme-terminal#153]
I wanted to enable Fira Code ligature function. Is there any possible way to do so?

**Comment by anildemir** [comment]
There is a CSS property called font-feature-settings. The ligatures can be enabled as following: 
```css
font-feature-settings: "liga" 1;
```

You can check these for more information:
https://developer.mozilla.org/en-US/docs/Web/CSS/font-feature-settings
https://developer.mozilla.org/en-US/docs/Web/CSS/font-variant-ligatures

**Comment by hdevilbiss** [comment]
You can do it with vanilla CSS property [font-variant-ligatures](https://developer.mozilla.org/en-US/docs/Web/CSS/font-variant-ligatures).

```css
code {
  font-variant-ligatures: normal;
}
```

**Comment by srevinsaju** [comment]
Thanks
