### ISSUE TITLE
Issue With Gist Display

### ISSUE THREAD

**Issue by bonedaddy** [panr/hugo-theme-terminal#156]
I seem to be getting issues being unable to display gist in certain portions of my content. For example the following code should display a gist but when viewed through a deployment it does not show up:

https://github.com/bonedaddy/blog/blob/master/content/random/gist.md

A deployed version for which is does not work https://bonedaddy.io/random/gist/

**Comment by panr** [comment]
Hmm... it works on my local setup:

<img width="861" alt="image" src="https://user-images.githubusercontent.com/1303365/85229792-2903f380-b3ec-11ea-8d7e-858c9c1aee5c.png">

**Comment by bonedaddy** [comment]
Yea it's really weird, it works on some pages of mine, including ones that I've overriden the default templates for, but this `random` section of my site has no overriden layouts, just the default `hugo-theme-terminal` ones and it doesnt seem to work.

**Comment by smailzhu** [comment]
I have same issue with line number

`{{< gist spf13 7896402 >}}`

![image](https://user-images.githubusercontent.com/9101328/100716349-84063180-33f3-11eb-8f6f-af31b37f8494.png)

**Comment by robbienohra** [comment]
same here the line numbers overlap with the gist code

**Comment by robbienohra** [comment]
@smailzhu @panr I found the offending CSS it's from the `table` class in  `styles.css` 

```css
table {
    table-layout: fixed;
    border-collapse: collapse;
    width: 100%;
    margin: 40px 0
}
```

Specifically `table-layout: fixed`. Removing that seems to resolve the text overflow issue.

**Comment by robbienohra** [comment]
@panr  let me know if this will cause a breaking change elsewhere in the theme. Otherwise I can change it to `auto` and submit a PR.

**Comment by robbienohra** [comment]
The 100% table width also squishes the gist line numbers against the code.

We can target the gist styling directly actually using these classes:

[gist-syntax-themes](https://cdn.rawgit.com/lonekorean/gist-syntax-themes/848d6580/stylesheets/monokai.css)

I was able to fully customize the gist styling this way without breaking the markdown table styles and correct the overflow issue.

Trying to think of what the most appropriate change would be to integrate into the theme.

But yeah good to have identified the issue!

**Comment by robbienohra** [comment]
Example for reference:

![image](https://user-images.githubusercontent.com/28514482/102738519-5e948580-4318-11eb-93fc-4c11b9444e88.png)

**Comment by robbienohra** [comment]
Before:

![image](https://user-images.githubusercontent.com/28514482/102738694-e1b5db80-4318-11eb-8888-1e72cb932025.png)

**Comment by panr** [comment]
@robbienohra could you raise a PR for this? 😎

**Comment by robbienohra** [comment]
💯
