### ISSUE TITLE
Mismatched color theme and all caps letters

### ISSUE THREAD

**Issue by GideonWolfe** [panr/hugo-theme-terminal#157]
When viewing my site from Firefox, I notice that the theme sometimes loads incorrectly, and all text on the page is capitalized.

I have seen this many times while writing content with a local Hugo server, but this is a screenshot I received from a friend who was viewing my site.

![theme](https://user-images.githubusercontent.com/32942052/85645201-e6415600-b64d-11ea-87ba-c1c764792af0.png)

**Comment by panr** [comment]
Need more info: 
- link to the page/site
- browser/OS info
- any other useful stuff (like what font is showing up in the browser devtools)

**Comment by panr** [comment]
I see that you're using some old version of the theme (so the changes I've done recently are not related) and when I go to your website everything looks fine (colors, fonts etc.).

**Comment by GideonWolfe** [comment]
Yeah I have trouble replicating it, it seems to happen intermittently.

The system from the screenshot is 
* https://www.gideonwolfe.com
* Arch Linux
* Firefox

**Comment by GideonWolfe** [comment]
So I updated the terminal theme directory and regenerated my site. Fired it up in chromium which I rarely use.

Seems like the right color is loading, but you can see that the main feed as well as the posts are in all caps.

![Screen Capture_select-area_20200625124057](https://user-images.githubusercontent.com/32942052/85788085-403f2b80-b6e1-11ea-90e2-3ba88ca5d9d5.png)
![Screen Capture_select-area_20200625124342](https://user-images.githubusercontent.com/32942052/85788251-872d2100-b6e1-11ea-97f8-df1fca30e280.png)

**Comment by panr** [comment]
I got this on your site:
<img width="677" alt="image" src="https://user-images.githubusercontent.com/1303365/85805482-b88f0680-b74c-11ea-9c98-e37e678a49a2.png">

**Comment by GideonWolfe** [comment]
Hmm do you have any idea what could cause this?

**Comment by GideonWolfe** [comment]
Ok I realize that the site only breaks when it is accessed with `www.` prepended to it. Still have no clue how to go about fixing it. Something with the site root?

**Comment by panr** [comment]
You can handle this via .htaccess, redirecting from `www` to `https`:
https://htaccessbook.com/htaccess-redirect-https-www/

**Comment by GideonWolfe** [comment]
`.htaccess` is for apache, no? How would I do it for NGINX?

**Comment by GideonWolfe** [comment]
Fixed with adding 
`add_header 'Access-Control-Allow-Origin' '*';`

under location in my server config.
