### ISSUE TITLE
Homepage Text Help

### ISSUE THREAD

**Issue by RaZnAr0k** [panr/hugo-theme-terminal#159]
Good Day!

I wanna ask about how you were able to add like a welcome banner on the home page of the sample website, and I'm looking around the code of the theme and I don't really seem to find anything about adding text to the home page. All I got out of it was this while doing inspect element, and this came out from your sample website [(which is located in this link)](https://hugo-terminal.now.sh/):
```
<div class="index-content framed">
      <h1 id="hello-there">Hello there!</h1>
<p>Welcome in demo of the <code>Terminal</code> theme. Please, look around and check whether this is what you are looking for.</p>
</div>
```

This actually appears before the recent posts code.

and in the `layouts/_default/index.html`, i saw this:
```
  {{ if .Content }}
    <div class="index-content {{ if .Params.framed -}}framed{{- end -}}">
      
      {{ .Content }}
    </div>
  {{ end }}
```

This is also located before the `<div class="posts">` tag, same as from your sample website.

I don't really get it that much, but that is probably the only thing I would really want to have on my page.

I hope you would help me with this problem.

Thank you for your time.

**Comment by panr** [comment]
Hi, I added the content for the banner in `content/_index.md` (`content` dir refers to the **index** page):

```.md
+++
framed = true
+++

# Hello there!

Welcome in demo of the `Terminal` theme. Please, look around and check whether this is what you are looking for.
```

You can add whatever you want before each "list type" page by adding `_index.md` file in the section directory, eg: `content/posts/_index.md` for `https://your-domain.com/posts/`.

**Comment by RaZnAr0k** [comment]
Hello! Thanks a lot! That really helped.
