### ISSUE TITLE
Code block doubt

### ISSUE THREAD

**Issue by rmartinsanta** [panr/hugo-theme-terminal#163]
Why in the showcase (https://hugo-terminal.now.sh/showcase) the CSS code can be minimized but neither the JS and the HTM can be?
As far as I can see in the source  they are using the same markdown syntax. (https://raw.githubusercontent.com/panr/hugo-theme-terminal/master/exampleSite/content/showcase.md)

Thanks in advance

**Comment by panr** [comment]
It's because https://hugo-terminal.now.sh/showcase is my own custom demo (where I'm using `{{< code >}}` shortcode for the first block of code), and the https://raw.githubusercontent.com/panr/hugo-theme-terminal/master/exampleSite/content/showcase.md is for the official Hugo Themes Demo.

**Comment by rmartinsanta** [comment]
I see, thanks!

What would be the source code required to render the block of code as the first CSS block?

Using 
```
{{< code javascript >}}
function get(url, callback)
{
// whatever
}
{{< /code >}}
```

does not render anything.

Thanks in advance.

**Comment by panr** [comment]
The full example of the `code` shortcode is in the README: https://github.com/panr/hugo-theme-terminal#built-in-shortcodes

**Comment by rmartinsanta** [comment]
Thanks, closing!
