### ISSUE TITLE
Extend prism.js to support more languages (or plugins)

### ISSUE THREAD

**Issue by tamasgal** [panr/hugo-theme-terminal#17]
I love your theme!

I am a hugo newbie, can you sketch how to update the `prism.js` library in your theme? I wanted to add `julia` so I downloaded the `js` and `css` [from here](https://prismjs.com/download.html#themes=prism-tomorrow&languages=markup+css+clike+javascript+actionscript+apacheconf+applescript+c+csharp+bash+cpp+coffeescript+ruby+csp+css-extras+diff+django+docker+markup-templating+elixir+elm+erlang+fsharp+flow+git+go+graphql+less+handlebars+haskell+http+java+php+json+julia+kotlin+latex+markdown+makefile+typescript+objectivec+ocaml+perl+php-extras+sql+processing+protobuf+scss+python+r+jsx+reason+textile+rust+sass+stylus+scheme+twig+swift+yaml+haml+toml+pug+tsx+visual-basic+vim+wasm&plugins=line-numbers+toolbar+jsonp-highlight+command-line+copy-to-clipboard). Then I searched in the folder structure and found the files:

```
./source/css/prism.css
./source/js/prism.js
```

I replaced them but those are somehow ignored.

I also found another file which seems to be the one used in the rendering process (in `/static/assets/prism.js` but I don't know how to generate it).

**Comment by panr** [comment]
Hi @tamasgal. I think you could replace `source/js/prism.js` and then run `yarn build`. This should work 😉 

Maybe there will be some fixes on CSS, but I hope not, because my "Prism CSS" is custom made and it required some changes...

**Comment by tamasgal** [comment]
Worked like a charm, thank you ;)
