### ISSUE TITLE
Footer positioning doesn't change

### ISSUE THREAD

**Issue by cskwrd** [panr/hugo-theme-terminal#173]
Footer remains "aligned" to the left regardless of `fullWidthTheme` or `centerTheme` being set to `true`.

To me it seems like the footer should always be centered relative to the content.

**Comment by HS-code17** [comment]
Having the same issue!

**Comment by panr** [comment]
It's not an issue. You can align the footer by yourself using `static/style.css` file workaround (look at README to find more).
