### ISSUE TITLE
Netlify complaining about babel (Hugo Pipes?)

### ISSUE THREAD

**Issue by willstocks** [panr/hugo-theme-terminal#185]
Hey @panr, I hope you're well!

I just happened to pull down the latest theme update and my test deploy to Netlify complains about the following:

```
2:45:32 PM: ┌────────────────────────────────────┐
2:45:32 PM: │ 1. build.command from netlify.toml │
2:45:32 PM: └────────────────────────────────────┘
2:45:32 PM: ​
2:45:32 PM: $ hugo --gc --minify --buildFuture -b $DEPLOY_PRIME_URL
2:45:33 PM: Building sites … ERROR 2020/08/24 13:45:33 BABEL: failed to transform "js/menu.js" (application/javascript). You need to install Babel, see https://gohugo.io/hugo-pipes/babel/
2:45:33 PM: ERROR 2020/08/24 13:45:33 JSBUILD: failed to transform "js/prism.js" (application/javascript): Could not resolve "clipboard"
2:45:33 PM: Total in 212 ms
2:45:33 PM: Error: Error building site: POSTCSS: failed to transform "css/style.css" (text/css): resource "css/css/style.css_23cbd773103b4c27602bf83ce1d529de" not found in file cache
```

I'm going to assume this is related to moving to 0.74+ and Pipes?

For reference, my `netlify.toml` is (all I did was change `HUGO_VERSION` to the latest release):
```
[build]
command = "hugo --gc --minify"
publish = "public"

[context.production.environment]
HUGO_ENABLEGITINFO = "true"
HUGO_ENV = "production"
HUGO_VERSION = "0.74.3"

[context.split1]
command = "hugo --gc --minify --enableGitInfo"

[context.split1.environment]
HUGO_ENV = "production"
HUGO_VERSION = "0.74.3"

[context.deploy-preview]
command = "hugo --gc --minify --buildFuture -b $DEPLOY_PRIME_URL"

[context.deploy-preview.environment]
HUGO_VERSION = "0.74.3"

[context.branch-deploy]
command = "hugo --gc --minify -b $DEPLOY_PRIME_URL"

[context.branch-deploy.environment]
HUGO_VERSION = "0.74.3"

[context.next.environment]
HUGO_ENABLEGITINFO = "true"
```

**Comment by panr** [comment]
@willstocks do you have `package.json` file in the root of your website? It should be created during the installation process https://github.com/panr/hugo-theme-terminal#how-to-run-your-site

**Comment by willstocks** [comment]
@panr there's not one in my root, but there is in `/themes/terminal/` which appears to contain all of the dependencies.

I definitely have those packages installed globally on my machine (I use them elsewhere) but assume the issue is the lack of `package.json`?

Any recommendation on the best way to generate one, or standard `npm init` and then manually define (or copy the content over from the `/themes/terminal/` file?

**Comment by panr** [comment]
Hugo Pipes (unfortunately) work differently... You need first run in your root dir:

```
npm i @babel/cli @babel/core @babel/preset-env browserslist clipboard cssnano postcss-cli postcss-import postcss-mixins postcss-nested postcss-preset-env postcss-url
```

This will install needed dependencies (those need to be in the root, the `package.json` in `theme/terminal` doesn't matter here) and create `package.json` which will be used by Netlify and your local Hugo server to run the Pipes.

**Comment by willstocks** [comment]
Ahhhh, gotcha!!! 

That has done the trick - I'll be honest, I had _completely_ overlooked the instructions 🤣

Thank you for your help - *speedy* as always 😄

**Comment by willstocks** [comment]
Do you want me to submit a PR to tweak the `readme` slightly to include a "if you're upgrading to Hugo 0.74+,..." for the `npm i` line?

**Comment by panr** [comment]
@willstocks just did it, let me know if the changes are enough :-)

**Comment by willstocks** [comment]
Perfect, thank you very much ☺️☺️
