### ISSUE TITLE
How was this "Hello there!" section done on the official website?

### ISSUE THREAD

**Issue by Weetile** [panr/hugo-theme-terminal#187]
I want to have a bit of text before the posts using this theme. Is there anyway to do it like this? 
![image](https://user-images.githubusercontent.com/7700383/91468163-82275200-e889-11ea-8864-3899d7fe9b46.png)

Also is there any way to have it without the orange border around it? Thanks.

**Comment by DHowett** [comment]
It looks like this is just a normal page with the `index` layout.

https://github.com/panr/hugo-theme-terminal/blob/0aae2e9ff48ff4a49f40f1a3f973f69af3aba408/layouts/_default/index.html#L3

If you add `framed = true` to your front matter, you can enable (or disable, which is the default) the frame.

![image](https://user-images.githubusercontent.com/189190/91529593-6be7b900-e8be-11ea-84da-16a4571a2c45.png)

```
+++
layout = "index"
framed = true
+++

# Hello world!
This is a page that pretends to be the `Terminal` showcase.
```

**Comment by Weetile** [comment]
Thank you very much @DHowett! It took me a while because I'm new to using static site generators, and subsequently Hugo, but I finally figured it out.

(To anyone reading this post-mortem, you can accomplish this by creating an `_index.md` file inside the content directory.)

**Comment by jimmyhess** [comment]
Would it be beneficial to use `_index.md` on the first page of posts and not the following pages?

**Comment by varun-s22** [comment]
> It looks like this is just a normal page with the `index` layout.
> 
> https://github.com/panr/hugo-theme-terminal/blob/0aae2e9ff48ff4a49f40f1a3f973f69af3aba408/layouts/_default/index.html#L3
> 
> If you add `framed = true` to your front matter, you can enable (or disable, which is the default) the frame.
> 
> ![image](https://user-images.githubusercontent.com/189190/91529593-6be7b900-e8be-11ea-84da-16a4571a2c45.png)
> 
> ```
> +++
> layout = "index"
> framed = true
> +++
> 
> # Hello world!
> This is a page that pretends to be the `Terminal` showcase.
> ```

hey @DHowett @Weetile I'm new to this, can you help me in figuring out where should i add these params?
is it on my `config.toml` or is it on my `layouts/_defaults/index.html`?, and if its in html which div should i add these attributes to?
