### ISSUE TITLE
The mobile menu button displays the desktop menu at 684px screensize

### ISSUE THREAD

**Issue by anildemir** [panr/hugo-theme-terminal#192]
Below 684px width, the mobile menu button is displayed and clicking on it displays the mobile menu. Above that value, the desktop menu is shown without the mobile menu button. However, right at 684px, the menu button is there and it toggles the desktop menu when clicked. It would be better to adjust the behavior to one of the first two cases for consistency. See the screenshots below from the demo site.

![682](https://user-images.githubusercontent.com/7266584/93898061-552c5a80-fce2-11ea-8688-23fcbd7e8d8e.png)
![684](https://user-images.githubusercontent.com/7266584/93898064-565d8780-fce2-11ea-8a26-4ee827c970bd.png)
![686](https://user-images.githubusercontent.com/7266584/93898067-56f61e00-fce2-11ea-90f0-85871a5e3e97.png)

**Comment by panr** [comment]
Thanks for catching that! Just fixed it 👍
