### ISSUE TITLE
Feature request: different color theme per post

### ISSUE THREAD

**Issue by SaulAryehKohn** [panr/hugo-theme-terminal#20]
Would it be possible to include an option for custom colors per post?

**Comment by panr** [comment]
@SaulAryehKohn Why not... Maybe you want to contribute on this?

**Comment by SaulAryehKohn** [comment]
Sure! I'm pretty new to Hugo but I bet I could figure it out.

**Comment by panr** [comment]
Little hint: we should use post param, eg. `color = ”red”` and in `single.html` override CSS variable `—accent`. But if you have a better solution, I’m open 😉

**Comment by SaulAryehKohn** [comment]
I'm on it! Also on vacation for 10 days, but I'd love to make this contribution.

**Comment by sotoka** [comment]
did you make the contribution ?

**Comment by SaulAryehKohn** [comment]
@sotoka I got started but never found time to finish it off.
