### ISSUE TITLE
[Documentation/Suggestion] How to add color theme

### ISSUE THREAD

**Issue by sophiabrandt** [panr/hugo-theme-terminal#200]
In issue #199 you described how to add a new color theme to hugo-theme-terminal. Thank you!
This _almost_ worked (I had to add the theme to the `webpack.config`, too).

I think that adding new colors might be of interest for others.

I would like to add the steps to the README if you are amendable to the addition.

Thank you.

**Comment by panr** [comment]
You are right, that's the missing info in the README. I will fix it! Thanks for reporting that 🤗
