### ISSUE TITLE
[Bug] apple-touch-icon 404 errors

### ISSUE THREAD

**Issue by sophiabrandt** [panr/hugo-theme-terminal#201]
In `layouts/partials/head.html` on line 24:
```html
<link rel="apple-touch-icon" href="{{ "img/apple-touch-icon-192x192.png" | absURL }}">
```
Where does the touch icon come from? Webpack doesn't generate it automatically as far as I know.
On my live site and also on the https://hugo-terminal.now.sh/ example, I'm getting a 404 error.

Maybe a webpack plugin would help? I found this one: https://github.com/jantimon/favicons-webpack-plugin

I could give it a try to add it to the theme if you like.

**Comment by panr** [comment]
Oh crap... The file doesn't exist 🤦. 

 > I could give it a try to add it to the theme if you like.

That would be super cool! I'd go with bare minimum for the plugin setup to not overload users with the assets ;-)

**Comment by sophiabrandt** [comment]
Hello, I totally forgot to tackle this. 😅
I will look into it when I have time. I am still interested in contributing, just to let you know.

**Comment by sophiabrandt** [comment]
According to my research, there are two ways to _automatically_ generate a Hugo favicon:
1. via Hugo pipelines
2. via Webpack

As far as I've understood it, Hugo pipelines are out of question for this theme, due to the inherent problem, see issue #199 .

I'm not very familiar with webpack. It seems to me that one could either write the webpack configuration oneself, or use the [aforementioned plugin](https://github.com/jantimon/favicons-webpack-plugin).

I'm not sure if I could do a better job than using the plugin.

Question:
Should I go ahead and try to integrate the Webpack plugin into the theme? 

> That would be super cool! I'd go with bare minimum for the plugin setup to not overload users with the assets ;-)

Do I understand you correctly that you _do not_ want to add another plugin to webpack?
