### ISSUE TITLE
languageSelector.js not found when set showLanguageSelector to true

### ISSUE THREAD

**Issue by Conight** [panr/hugo-theme-terminal#204]
If I copy languageSelector.js from `assets/js` to `static/assets`, it will be loaded but cannot show language dropdown when using pc browser.

![image](https://user-images.githubusercontent.com/12389161/96820500-b027ad80-1458-11eb-9e1b-cdd5844b175d.png)

**Comment by panr** [comment]
Oh, damn. Sorry for that 😭 Just fixed it here — https://github.com/panr/hugo-theme-terminal/commit/480cb601503efec92e8803023e54c16b4c3c571b
