### ISSUE TITLE
empty summary for manual split

### ISSUE THREAD

**Issue by bboehmke** [panr/hugo-theme-terminal#209]
If a [manual summary split](https://gohugo.io/content-management/summaries/#manual-summary-splitting
) is used, the resulting post contains no summary in the list:
![image](https://user-images.githubusercontent.com/9787279/97789999-4ed4ac80-1bc5-11eb-9eac-a3202e2968f5.png)

To reproduce simply add a `hello2.md` file with the following content to the example site:
```
+++
title = "Hello Friend2"
date = "2019-02-25"
author = "Lorem Ipsum"
+++

Lorem ipsum dolor sit amet, consectetur adipiscing elit. 

<!--more-->

Nullam nec interdum metus. Aenean rutrum ligula sodales ex auctor, sed tempus dui mollis. Curabitur ipsum dui, aliquet nec commodo at, tristique eget ante. 
```

**Comment by panr** [comment]
Hmm... weird.. Just checked it on my setup and with this:

<img width="980" alt="image" src="https://user-images.githubusercontent.com/1303365/99192536-a5201e80-2773-11eb-9a07-75cf5149348f.png">

I got:

<img width="853" alt="image" src="https://user-images.githubusercontent.com/1303365/99192546-aea98680-2773-11eb-8c39-17889d4cc8fd.png">

So it looks that it works 🤔

**Comment by bboehmke** [comment]
Strange, for me it is not working. It seems now also not working for automatic split.

I build up a example that demonstrate the issue based on the provided example: https://github.com/bboehmke/terminals_exampleSite

You can see (or not see) the summary in the build site at:
* automatic: https://github.com/bboehmke/terminals_exampleSite/blob/master/public/index.html#L149
* manual: https://github.com/bboehmke/terminals_exampleSite/blob/master/public/index.html#L178

I used hugo v0.78.1 on a linux to build the site.

Also this is maybe related to this issue gohugoio/hugo#7926 I found (but here I am not sure because I am new to hugo)

I hope this helps to reproduce the issue.

**Comment by bboehmke** [comment]
I also tested it on windows with hugo v0.78.2 on windows with the same result.

**Comment by bryceyang** [comment]
same issue here. manually split not working.

<img width="860" alt="Screen Shot 2020-12-06 at 10 37 11 PM" src="https://user-images.githubusercontent.com/9302617/101283133-a04f0780-3813-11eb-9e70-41a6aeba7634.png">

**Comment by hamptonmoore** [comment]
I am also having this issue
