### ISSUE TITLE
Configure what shows up on home page snippet

### ISSUE THREAD

**Issue by levlaz** [panr/hugo-theme-terminal#21]
Hi! I really love this theme. Although I a bit confused on how to configure what shows up on the home page. 

I see in the demo site you have a description field, however, is it possible to use the first paragraph as the description rather than duplicating it? Also, is it possible to just show the entire post content on the home page?

**Comment by levlaz** [comment]
Nevermind, sorry I am new to hugo! 

If anyone else runs into this. Per the huge docs: https://gohugo.io/content-management/summaries/#automatic-summary-splitting

> By default, Hugo automatically takes the first 70 words of your content as its summary and stores it into the .Summary page variable for use in your templates. 

This theme uses .Summary like so if the .Description is not set: 

```
      <div class="post-content">
        {{ with .Description }}
          {{ . | markdownify }}
        {{ else }}
          {{ if .Truncated }}
            {{ .Summary | markdownify }}
          {{ end }}
        {{ end }}
      </div>
```

My test post had less than 70 words, so I suppose the hugo piece didn't know what to do.

**Comment by panr** [comment]
Exactly, by default theme prints Summary, but you can override it by usuing Description param in post 😉
