### ISSUE TITLE
`diff` code blocks aren't highlighted

### ISSUE THREAD

**Issue by rdnlsmith** [panr/hugo-theme-terminal#211]
The README indicates that `diff` is supported, but when I tried e.g.

    ```diff
    -This is an old line
    +This is a new line
    ```

the text did not appear highlighted.

Split from #193; see also [#203 (comment)](https://github.com/panr/hugo-theme-terminal/pull/203#issuecomment-720002081).

**Comment by panr** [comment]
I've just fixed it and match to the theme syntax duotone color, so it's not gonna be a red/green but more like no-color/accent color.

**Comment by rdnlsmith** [comment]
Thanks!
