### ISSUE TITLE
Feature request: split code element

### ISSUE THREAD

**Issue by sardaukar** [panr/hugo-theme-terminal#22]
This theme is awesome and I use it to power my blog at https://blog.nootch.net thank you for your work.

I have a feature request, not sure if it makes sense. I post a lot of code, and for every file there is sometimes an associated test. It would be great to be able to have these occupy the same space with tabs to select between them so that blog posts are not so long. Here's some awful ASCII art to try and explain it:

   active tab --v                                                         
[ lib/something/file_name.ex ] | test/something/file_name_test.exs |
|
```
code for lib/something/file_name.ex
```
|_____________________________________________________

Do you think this makes sense? Thanks for any replies!

**Comment by panr** [comment]
Hmm... could you give me a link to the blog post where you want to have this feature?
As far as I understand this could be possible, but I need to create a shortcode for this...

**Comment by sardaukar** [comment]
I wanted to use this for an upcoming post which will feature a lot of code and some of those files will have a test associated.

**Comment by mohanboddu** [comment]
I think something like [code-toggle](https://gohugo.io/getting-started/code-toggle/) would be perfect for this.

But don't know how hard to create something like that.

**Comment by panr** [comment]
Nice! I'll make it soon!
