### ISSUE TITLE
How to switch bg-color from dark to light? 

### ISSUE THREAD

**Issue by Abdullahsams** [panr/hugo-theme-terminal#220]
Please help me, I prefer my blog is white background. Any ideas?

**Comment by Abdullahsams** [comment]
where is to change text content color?

**Comment by rampadc** [comment]
@Abdullahsams https://github.com/panr/hugo-theme-terminal/issues/46#issuecomment-753357558

**Comment by Abdullahsams** [comment]
@rampadc thank you so much dude!
