### ISSUE TITLE
how can i add a nav item in menu with a list page as posts

### ISSUE THREAD

**Issue by whidy** [panr/hugo-theme-terminal#23]
demo shows that menu only for single page.
how can i show two list in menu,,
i mean default list is posts, but needs another one list, look likes a categories.

**Comment by panr** [comment]
> demo shows that menu only for single page.

Hmm... yes, but you can add any link to any page/blog post/categories/external resources/anything you want... You can declare it in config file.

> how can i show two list in menu...

Right now you can't. It's only one `main menu`.

> i mean default list is posts, but needs another one list, look likes a categories.

By `list` you mean `Show more ▾` in menu? It displays because in config file I set `showMenuItems = 2`. Whole menu have 3 items — links to two pages and one blog post.

**Comment by whidy** [comment]
Sorry for my english, I don't know if I can do like this.

As default, homepage show us a list of posts folder.

Can i create another folder named `sport` or `animal` in content, like this

```
- content
|- posts
|- sport
|- animal
```

and three folder each contain many posts.

now, set `contentTypeName = "posts"` will display homepage with posts folder.

How can I set a link in menu, can open a page with sport posts list.

so menu will as below

```
About  showcase  Sport
```

click sport. url will be like `example.github.io/sport`

Thank for you help :D

**Comment by panr** [comment]
Oh I see... Right now you can't do this (at least without any additional effort to make another template index for new .Type of content, eg. `sport` or `animal`)*. I'm still working on this...

*BUT... you can do this manually by:
- copy `list.html` from `layouts/_default`
- create new folder `sport` and `animal` in `layouts`
- paste `list.html` to each folder
- change this line https://github.com/panr/hugo-theme-terminal/blob/master/layouts/_default/list.html#L5 to `{{ $paginator := .Paginate (where .Data.Pages "Type" "sport") }}` (just change the argument after "Type" word; do the same for `animal`)
- after this, you can delete line 3 and 4
- restart Hugo Server

Let me know if this works ;-)

**Comment by whidy** [comment]
Nice job!

It works perfect.

Thank you!!!

Here is my page<https://whidy.github.io/>. This should be a ask for hugo's help, but you helped me. thanks~

**Comment by panr** [comment]
@whidy feel free to make a contribution and add your site to this file ;-) https://github.com/panr/hugo-theme-terminal/blob/master/USERS.md (raw file will show file template)

**Comment by whidy** [comment]
@panr i am fixing another problem with git submodule. always fail with offical deploy.sh.

when i ready, i will help to contribute my site. lol
