### ISSUE TITLE
full posts in rss feed

### ISSUE THREAD

**Issue by MCWertGaming** [panr/hugo-theme-terminal#234]
Hello,
I want to include the full blogposts inside of my rss feeds and not only the summary. I have already done that by simply editing the rss template file of Hugo. I wanted to ask, if there is an easier way to do that.

Thank you very much!

Cheers!

**Comment by CMiksche** [comment]
I created a PR for that ;-)

**Comment by MCWertGaming** [comment]
Thank you really much!
