### ISSUE TITLE
[Feature Request] Add PWA files

### ISSUE THREAD

**Issue by MCWertGaming** [panr/hugo-theme-terminal#257]
I think that it would be cool to add the required files for making this theme a PWA and installable as one. This wuold probably just require adding a manifest.json and the worker as javascript file for making it available offline and maybe even send notifications on Android. I'm sadly really untallented in javascript, otherwise i'd open a pr on that. Maybe some one likes this idea and want's to implement it?

Also I'm not sure if hugo has the ability to add content into .json files, but if that was possible it would be really nice to have that in this theme.

**Comment by panr** [comment]
I will 👍
