### ISSUE TITLE
Feature Request: Add support for prismjs line highlight

### ISSUE THREAD

**Issue by mohanboddu** [panr/hugo-theme-terminal#26]
It would be great if line highlight plugin of prismjs is supported.

I am newbie here, esp with front end technologies, I saw the #17 but I dont know how to do an `yarn build` and found some [docs](https://yarnpkg.com/en/docs/cli/run) but not very much helpful since I dont know anything about it.

Along those lines, how I can call `data-start` attribute of `line-numbers` prismjs plugin?

I am using:

```
```javascript{line-numbers}{data-start:5}
```

But its not working :cry: 

Thanks.

**Comment by panr** [comment]
Oh, I don't have this plugin yet. I'll add this later this week!

**Comment by mohanboddu** [comment]
Thanks in advance for working on the highlight line plugin. 

But how to add the start number for already existing `line-numbers` plugin?

**Comment by panr** [comment]
I don't know if you can do it another way than directly by html — `<pre class="line-numbers" data-start="X"><code></code></pre>`

**Comment by mohanboddu** [comment]
```
<code class='language-python'>
<pre class="line-numbers" data-start="5">
for x in list:
    if x == y:
        print("Found x")
</pre></code>
```
Thanks, the above seems to be working. For anyone who wants to use it, they can use this as an example.

**Comment by funayman** [comment]
If you wanted, you could make your own shortcode for it.
I'm not sure how correct this is (I dont have the plugin to confirm), but give it a go if you'd like.

**layouts/shortcodes/prism.html**
```html
{{ if len .Params | eq 0 }}
  <pre><code>{{ .Inner }}</code></pre>
{{ else }}
  {{ if .IsNamedParams }}
    <pre
      {{ if .Get "lang" }}class="language-{{ .Get "lang" }}"{{ end }}
      {{ if .Get "line" }} data-line={{ .Get "line" }} {{ end }} >
    <code {{ if .Get "lang" }}class="language-{{ .Get "lang" }}"{{ end }}>
      {{ .Inner }}</code>
    </pre>
  {{ else }}
    <!-- used for language only. ie {{<prism python>}} -->
    <pre class="language-{{.Get 0 }}">
    <code class="language-{{.Get 0 }}">{{ .Inner }}</code>
    </pre>
  {{ end }}
{{ end }}
```
**content/posts/example.md**
```markdown
{{< prism lang="python" line="2" >}}
for x in list:
    if x == y:
        print("Found x")
{{< /prism >}}
```

**Comment by panr** [comment]
@funayman I love the idea of making the prism shortcode! Please contribute 🖤

**Comment by MarcoEpsilon** [comment]
@funayman I had tried your method,but you can see the result in the picture,i think you should try with js in your prism.html
![image](https://user-images.githubusercontent.com/46967791/60273402-ace5e580-9928-11e9-9545-e63b3122f358.png)
