### ISSUE TITLE
Can't get cover images to work

### ISSUE THREAD

**Issue by abhinav031** [panr/hugo-theme-terminal#274]
I have a few images i want to use as covers in static/img but they don't seem to display as images, rather I just see the file name inside a rectangle.
![Screenshot_2021-09-04-11_839x413](https://user-images.githubusercontent.com/73749351/132099014-4a23d02e-df14-498b-84ca-33ff59a81403.png)

**Comment by zgershkoff** [comment]
Is the file located in static/img? I discovered that I had to put /img/ in front of the file paths in order to make embedded images work.

I'd be curious to know why the example site doesn't work right out of the box anymore.

**Comment by panr** [comment]
Auto Cover and .Resources assets should work from now ;-)
