### ISSUE TITLE
Documentation of GitHub actions

### ISSUE THREAD

**Issue by ChrisBeeley** [panr/hugo-theme-terminal#275]
First thing to say- love the theme, thanks!

I just spend an extremely long time getting this theme to work with GitHub actions, mainly because I didn't really have a clue what I was doing with npm dependencies etc. Would you like me to contribute a quick how to guide for getting it working with GitHub actions? I may not be doing it quite right because as I say I don't really know what I'm doing (:smile:) but it might help other people like me who can get it working really easily with `hugo server` but not at all with GitHub Actions

**Comment by panr** [comment]
Cool, let me if it works ;-)
