### ISSUE TITLE
Feature request : replace PrismJS with Chroma

### ISSUE THREAD

**Issue by Miaourt** [panr/hugo-theme-terminal#29]
Hugo come with a built-in syntaxt highlighter that allow you to pre-built hightlight and remove a JS dependencies :)
https://gohugo.io/content-management/syntax-highlighting/

**Comment by panr** [comment]
Chroma should work fine because it's Hugo's default syntax highlighter 🤔 
...but... I use Prism because I made custom syntax colors that match the color of the theme...

If you know how to create a custom Chroma syntax highlighting that will match the theme color, please contribute 😉

**Comment by compcs** [comment]
Can there be a option to disable PrismJS and use Chroma, like this can remain disabled by default and used by someone who wants to use chroma [btw, prism doesn't highlight fortran code properly]
