### ISSUE TITLE
How disable comments on specific pages?

### ISSUE THREAD

**Issue by shirou93** [panr/hugo-theme-terminal#298]
When i enable disqus on all pages got comments.

**Comment by panr** [comment]
You have to check the official documentation of [Hugo](https://gohugo.io/content-management/comments/). I guess you have to override the internal template for the comments and add some conditional to stop rendering the comment form/block. OR (this is only my assumption) you can prevent the `comments` partial from including the `{{ template "_internal/disqus.html" . }}` when you need it — something like:

```
{{ if ne (.Params "hideComments") true }}
    {{ template "_internal/disqus.html" . }}
{{ end }}
```

which means: if you put `hideComments = true` in your page's front matter, then you are not going to see the comments section.

Keep in mind that I didn't test it...

**Comment by shirou93** [comment]
I add
`---
title: "O Mnie"
date: 2021-11-14T22:06:44+01:00
draft: false
hideComments: true
---
`
and still got comment in bottom.

**Comment by shirou93** [comment]
other templates have:
![image](https://user-images.githubusercontent.com/59237288/141840058-d3798a37-001a-4518-a86b-76f9d3a22a94.png)

**Comment by shirou93** [comment]
It's look like theme shuld suport this feature:
https://www.mpaulacaldas.com/post/2020/03/25/hello-hugo-xmin-comments/

**Comment by panr** [comment]
Did you update the comments partial as I showed you above? It should work 🤔

**Comment by shirou93** [comment]
> Did you update the comments partial as I showed you above? It should work 🤔

Your code not work, some error when try build website.

I tried
`{{ if not .Params.disable_comments }}
{{ template "_internal/disqus.html" . }}
{{ end }}`

and disable_comments: true. Working like charm. Thanks for directing me
