### ISSUE TITLE
Tried to deploy site on Netlify but the build keeps failing because of submodule issues

### ISSUE THREAD

**Issue by Uzoamaka126** [panr/hugo-theme-terminal#299]
Trying to deploy my site on Netlify but the build keeps failing because Netlify can't fetch a particular commit: aebcb25911b39b042833223b7e5b48957fef2dc2

The Netlify logs show errors like this: 
`Failed during stage 'preparing repo': Error checking out submodules: Submodule 'themes/terminal' (https://github.com/panr/hugo-theme-terminal.git) registered for path 'themes/terminal'`

`Fetched in submodule path 'themes/terminal', but it did not contain aebcb25911b39b042833223b7e5b48957fef2dc2. Direct fetching of that commit failed.`

I tried adding this repo to my project by cloning it as the instructions on the readme suggested. Same error.

I also tried using it as a submodule. Same error too.

**Comment by panr** [comment]
Hmmm... there's no commit with that hash in my repo 🤔 

Have you tried to clean the cache for that particular deploy?

**Comment by Uzoamaka126** [comment]
Yeah, I did. Cleared the cache before I redeployed and the issue still persists.

**Comment by panr** [comment]
OK, so... did it work before, or is it the first time you used the theme to deploy on Netlify?

**Comment by crazymonkyyy** [comment]
this is probably supposed to be solved a different way, but if you look your not uploading the theme to github it has some sort of complex relationship; so something something netifly isn't getting the theme files

if you delete /themes/terminal/.git and then repush, netify will get the theme files; this has been true for the 3 themes I've tried
