### ISSUE TITLE
[Suggestion] Add option disable post trucation on index

### ISSUE THREAD

**Issue by MoritzFago** [panr/hugo-theme-terminal#30]
I'd like to disable the post truncation on the index. [I tried to](https://github.com/MoritzFago/hugo-theme-terminal), but this creates bugs with pre-blocks.

**Comment by panr** [comment]
@MoritzFago You can now add in post file `showFullContent = true` param

**Comment by MoritzFago** [comment]
I am sorry, i wasn't clear in what I wanted, I wanted to disable the truncation globaly
