### ISSUE TITLE
Fira Code included?

### ISSUE THREAD

**Issue by dricard** [panr/hugo-theme-terminal#305]
Is Fira Code included in the theme? I don't see ligatures that I normally see in Fira Code, like -> turning into a proper arrow. I suppose there is code in the CSS to fetch the fonts?

**Comment by panr** [comment]
Yes, it is, here — https://github.com/panr/hugo-theme-terminal/tree/master/assets/fonts. 

And good catch, I use mainly a Unicode character `→` for arrows but just checked what could prevent `->` from being transformed to an arrow ligature and found that "case" in `font-feature-settings` is causing the issue 🤔 

Just pushed a commit (https://github.com/panr/hugo-theme-terminal/commit/411fade4c6b9aabadd69ff3d0854739a74a1c014) that should fix it, could you confirm?

**Comment by dricard** [comment]
Yep that did the trick! Thanks for the quick update. Great theme!

Best regards,
Denis
