### ISSUE TITLE
Use other fonts than fira code?

### ISSUE THREAD

**Issue by wmcbtech30** [panr/hugo-theme-terminal#307]
Fira is good but i wanted to use other Terminal fonts like Iosevka on my website.
I could replace fira with other font file in `assets` directory but not sure how it renders correctly.

would be possible or implement to use other fonts than Fira code via config file or just replacing the font file would be enough?

**Comment by panr** [comment]
You can provide your own assets and override the font settings by adding them via custom `style.css`.

from README:

```
If you have to override only some of the styles, you can do this easily by adding "static/style.css" in your root directory and point things you want to change.
```

**Comment by wmcbtech30** [comment]
thanks for the answer
