### ISSUE TITLE
Feature Request: Option for multi language

### ISSUE THREAD

**Issue by Rinma** [panr/hugo-theme-terminal#31]
Hi,

I think it would be nice to have somewhere in the `header__inner` or `header` a field that shows the languages that are supported by the website so the visitor can choose which language he wants to see.

This option should be configurable by the config file if it is shown or not.

**Comment by panr** [comment]
Would you like to contribute on this?

**Comment by Rinma** [comment]
Ok I will do this 😄

**Comment by Rinma** [comment]
What happened here, why did it close when I experimented on my fork o.O ... This should not be closed until https://github.com/panr/hugo-theme-terminal/pull/33 is merged, sorry.
