### ISSUE TITLE
some params not documented

### ISSUE THREAD

**Issue by icy-comet** [panr/hugo-theme-terminal#313]
While scanning the layouts, I found that params like `Toc` and `readingTime` haven't been documented in the project's main README or the post archetype.

I don't know if this is intentional since the project follows `Releases` model. But if not, let me know and I would be happy to open a PR.

**Comment by panr** [comment]
Hmm... these params are Hugo's built-in params so I'm not sure whether they have to be documented in the theme's README 🤔 

But if you feel they should, then feel free to raise a PR for this 🙌

**Comment by panr** [comment]
I'm also aware that I should update the whole archetype/demo page structure for the project and make a few things simpler to be easier to understand to newcomers 😬

**Comment by icy-comet** [comment]
I understand that Hugo provides this info. However, the way our layouts are setup, we can control whether to show this info or not on a per-page basis. That is not a built-in Hugo template/feature/option.

I personally thought that the theme lacked a `ToC` section until I saw the `single` layout. So, maybe documenting it would be a good idea 😀
