### ISSUE TITLE
use Hugo's internal templates for Open Graph and Twitter Card data

### ISSUE THREAD

**Issue by icy-comet** [panr/hugo-theme-terminal#315]
I was wondering the reason behind not using Hugo's internal Open Graph and Twitter Card templates.

I compared the current open graph data and [Hugo's internal template](https://github.com/gohugoio/hugo/blob/master/tpl/tplimpl/embedded/templates/opengraph.html), and it seems `og:image:height`, `og:image:width` and `article:section` are the only properties conflicting with the internal one. The current one misses a property or two as well.

Similarly, Hugo's [internal Twitter Card template](https://github.com/gohugoio/hugo/blob/master/tpl/tplimpl/embedded/templates/twitter_cards.html) seems a bit more comprehensive than the current one.

Either we could switch to using the internal templates or maintain separate partials similar to the internal one.

**Comment by icy-comet** [comment]
If there isn't a particular reason to hold back using internal templates, I could submit a PR regarding this. @panr

**Comment by panr** [comment]
I believe it is. People were not happy with the standard template, so we changed it to match the theme's needs. If there's something missing, please raise a PR ;-)
