### ISSUE TITLE
table of contents shouldnt show up on small posts

### ISSUE THREAD

**Issue by crazymonkyyy** [panr/hugo-theme-terminal#321]
![2022-03-01-233401_415x118_scrot](https://user-images.githubusercontent.com/5334907/156308205-f5a87ae7-7acf-4577-91f2-f32e264623cc.png)

```
[params]
  contentTypeName = "posts"
  themeColor = "blue"
  showMenuItems = 2
  readingTime = true
  centerTheme = true
  Toc = true
 ```

**Comment by Gymnae** [comment]
Uhm, then simply set TOC to false?

**Comment by crazymonkyyy** [comment]
thats a global setting and I have both big posts and shit posts :shrug:

**Comment by Gymnae** [comment]
> thats a global setting and I have both big posts and shit posts 🤷

nope, you can set it per post in the frontmatter
