### ISSUE TITLE
Terraform syntax highlight 

### ISSUE THREAD

**Issue by mpostument** [panr/hugo-theme-terminal#323]
Hello, does it possible to add terraform syntax highlight?

**Comment by mpostument** [comment]
How can I use terraform syntax highlight? I tried to use terraform and tried HCl as prims js doc said. But I don't see any syntax highlighting. https://mpostument.com/2022/09/11/terraform-condition-and-lookup/

**Comment by panr** [comment]
Sorry, but I'm neither not providing any support in terms of 3rd party libraries nor Hugo itself.
