### ISSUE TITLE
[Question] Colored background from demo site

### ISSUE THREAD

**Issue by ae5960e8-a6fc-491f-b252-898ecf59af95** [panr/hugo-theme-terminal#325]
Hi, I'm trying to find how to achieve this look shown on the demo instance of the theme, but I haven't had much luck.
https://hugo-terminal.vercel.app/posts/rich-content#twitter-simple-shortcode
Thanks!

**Comment by MikeFoden** [comment]
@ae5960e8-a6fc-491f-b252-898ecf59af95 have you set your theme params to set the `themeColor` to **orange**?
