### ISSUE TITLE
Is this theme able to add a graphic design logo?

### ISSUE THREAD

**Issue by linuxgamingcentral** [panr/hugo-theme-terminal#328]
Hi, you'll have to forgive me since I'm a bit rusty with web development. I just got a logo for my website and was curious how to add it to the top of the page? I have the source code for the site available [here](https://github.com/linuxgamingcentral/website) in case it helps.

If this isn't the right place to ask feel free to point me in the right direction.

**Comment by panr** [comment]
Here's the theme template partial for the logo section: https://github.com/linuxgamingcentral/website/blob/main/themes/terminal/layouts/partials/logo.html

You can override this inside your site's `layout` directory (check official Hugo's docs).
