### ISSUE TITLE
RSS feed

### ISSUE THREAD

**Issue by trombonefix** [panr/hugo-theme-terminal#329]
Hi, 
sorry for the beginner's question: how can I provide RSS feeds in this theme?  Is that possible in the config.toml file?

**Comment by panr** [comment]
Please check the official Hugo's documentation. It's pretty straightforward to add it ;-)

**Comment by trombonefix** [comment]
Thank you, that was stupid of me.

**Comment by panr** [comment]
No, it's totally fine to ask. I hope you find it ;-)
