### ISSUE TITLE
Add new language 

### ISSUE THREAD

**Issue by trombonefix** [panr/hugo-theme-terminal#330]
How can I set up a new language for the menu? 
I changed the following in the config.toml file: 

- showlanguageselector = true 
- created a new menu [languages] [languages.de]
- added the menu items [languages.de.menu] 

The problem is that whenever I choose German  Place and then click a menu item, it automatically reverts to English.

**Comment by panr** [comment]
Hey, you have to have content in that language as well, eg: `content/posts/de/...`
