### ISSUE TITLE
Cover images detected for post, but cover image missing from opengraph metadata

### ISSUE THREAD

**Issue by major** [panr/hugo-theme-terminal#334]
Thanks for all the hard work on this awesome theme! 👏🏻

I was able to get cover images working well with `autoCover`, but I'm having an issue with the opengraph metadata for social media posts. My `favicon.ico` appears in the page source instead of the cover image.

I see this inside `head.html`:

```html
{{ if and (not .IsHome) (isset .Params "cover") }}
  <meta property="og:image" content="{{ .Param "cover" | absURL }}">
{{ else }}
  {{ if isset $.Site.Params "favicon" }}
    <meta property="og:image" content="{{ $.Site.Params.favicon | absURL }}">
  {{ else }}
    <meta property="og:image" content="{{ printf "img/favicon/%s.png" $.Site.Params.ThemeColor | absURL }}">
  {{ end }}
{{ end }}
```

It looks like I would need to specify the cover image filename here to make it work. Would it be possible to bring over some of the `autoCover` code to make this work automatically? I'm tinkering a bit to see if I can figure out the logic myself.

**Comment by wgarbutt** [comment]
I also have this issue, did you happen to find a solution?
