### ISSUE TITLE
Is there a way to center everything

### ISSUE THREAD

**Issue by theloganlab** [panr/hugo-theme-terminal#343]
Im about to try out this template and i love it, the only thing i dislike is the huge blank space at the right, how can i make the text fill the whole screen or be centered:????

**Comment by christianfl** [comment]
Just change the config.toml:

```
# set theme to full screen width
fullWidthTheme = true
```

**Comment by pgronkievitz** [comment]
>    fullWidthTheme = true

more like
```
[params]
  centerTheme = true
```
