### ISSUE TITLE
How can i do this quote?

### ISSUE THREAD

**Issue by theloganlab** [panr/hugo-theme-terminal#352]
![Screen Shot 2022-07-08 at 4 38 48 PM](https://user-images.githubusercontent.com/107451329/178073843-b3775c5c-72c4-4fc3-9335-df195d587cb6.png)

**Comment by Erioldoesdesign** [comment]
Bump - I would also like to know how to use this quote in markdown as the default quote is different and we had to make a new shortcode to make a different pullquote style

**Comment by Umbragloom** [comment]
I can this exact quote from @DesignReviewed, to show when I have that exact tweet id set in the standard Hugo twitter shortcode, on the initial load of the page but it immediately loads the full card (showing image and quote) after a few seconds. I also cannot find any info besides what's in head.html for the Twitter Card. Does anyone know where this is located?

**Comment by elinx** [comment]
> I can get this exact quote from @DesignReviewed, to show when I have that exact tweet id set in the standard Hugo twitter shortcode, on the initial load of the page but it immediately loads the full card (showing image and quote) after a few seconds. I also cannot find any info besides what's in head.html for the Twitter Card. Does anyone know where this is located?

hugo support two shortcodes for twitter, use the `twitter_simple` one, and it will render what the op posted like.

ref: https://github.com/gohugoio/hugo/blob/master/tpl/tplimpl/embedded/templates/shortcodes/twitter_simple.html
