### ISSUE TITLE
[Bug?] Post published but homepage blank

### ISSUE THREAD

**Issue by codedeeply** [panr/hugo-theme-terminal#36]
Hi! I'm new to Hugo, so if this "bug" is simply something caused by error on my part, I apologize.

I love the look and feel of your Terminal theme! I recently started messing around with it, and created my first post -- but noticed despite the post being marked as `draft: false`, it doesn't show up on the homepage. The homepage itself is simply blank. I've tried modeling my post around the meta data in your simple website's post, but have had no luck.

My live site is [stlain.net](https://stlain.net), with the [first post here](https://stlain.net/post/hello-wired/). Here is my [config.toml](https://www.dropbox.com/s/sly1beg30uuleep/config.toml.txt?dl=0) file.

The post's header is as follows:
`---
title: "Hello Wired"
date: 2019-04-13T19:51:59-07:00
author: "codedeeply"
description: "This is a welcome and primer post -- it's the first on this site. A touch on the Wired and Cyber-Nihilism."
draft: false
---`

Thank you in advance for your assistance!

**Comment by codedeeply** [comment]
This is a non-issue with the theme -- user error was the result.

For those running in to this issue in the future, you need to add `type = "posts"` into your post metadata if you have `contentTypeName` declared.

**Comment by panr** [comment]
Hi @codedeeply `type = "posts"` isn't necessary. You can change `contentTypeName` to `post` in your `config.toml` or just change `content/post` to `content/posts`. `contentTypeName` is basically `content/[contentTypeName]`.

Also you can see a dev comment above the line in config → `# dir name of your blog content (default is `content/posts`)`

**Comment by codedeeply** [comment]
Got it, thanks for the help!!
