### ISSUE TITLE
How to get posts displaying on a page that is not the index page

### ISSUE THREAD

**Issue by Erioldoesdesign** [panr/hugo-theme-terminal#375]
Hi folks,

I've been looking across various people's edits of this theme and cannot find an obvious solution at all.

All I want to do is have an 'updates.md' page that pulls in the posts (which act like news/newest items) on our site and for those to not display on the main _index page. 

I see various people that have different posts displaying on different pages using posts for different content types e.g. news, updates, experience etc. by using folders in the content folder but I'm unsure what I change in the various .html/toml files in order to have this not throw errors :(

**Comment by Umbragloom** [comment]
Can you clarify a bit more about what your trying to achieve?

based on how I'm interpreting your issue :

1. You would like to have your main page not show the items of your posts but be something different? 
2. You would like to have your individual pages, linked through the menu, have their own posting stream?

or are you just looking for assistance on setting up the structure? Also what errors are you seeing?

**Comment by Erioldoesdesign** [comment]
> Can you clarify a bit more about what your trying to achieve?
> 
> based on how I'm interpreting your issue :
> 
> 1. You would like to have your main page not show the items of your posts but be something different?
> 2. You would like to have your individual pages, linked through the menu, have their own posting stream?
> 
> or are you just looking for assistance on setting up the structure? Also what errors are you seeing?

This is our minisite: https://simplysecure.github.io/devs-guide-to/

So on the main homepage/index page I want the border boxed info titled' Welcome to the USABLE.tools Adoptable resources project' only. Currently there are also posts that display under that info.

I'd like the posts that are listed in the main homepage/index page to be listed instead in this page: https://simplysecure.github.io/devs-guide-to/updates/ so that the 'blog/posts' updates are in a separate updates page.

Does that make sense? 

I'm unsure how I can remove the posts displaying in the main page (so what code I need to remove) to then have them show in the updates page (and what kind of layout template I should use for this)

**Comment by Umbragloom** [comment]
So I've done some quick testing.

Make a copy of the ```index.html``` file found in ```/themes/terminal/layouts/_default/``` that is located in your ```RootWebsiteFolder/layouts/_default``` folder. 

Locate the PageContext section and add the two lines below:

                                                                                   
``` html 
{{ $PageContext := . }}                                                     
     {{ if .IsHome }}                                                       
       {{ if not .IsHome }} <!-- ADD IN THIS LINE HERE                                                          
         {{ $PageContext = .Site }}                                                
    {{ end }}      <!-- ADD IN THIS LINE HERE                                                            
{{ end }}   
```

After saving, this made my main page look like this: 

![screen](https://user-images.githubusercontent.com/15257477/197074430-54ef738f-3eb5-4a93-b26f-be4a8b323ddd.png)

And other pages that are not the home page will still show lists as intended:

![screen1](https://user-images.githubusercontent.com/15257477/197082889-12588aa3-54c9-487d-81d2-d6f32e3e793f.png)

Instead of having the Updates as a post make it a folder in your ```content/posts/``` then move all of your actual posts into that folder and it will paginate them as intended.

**Comment by Erioldoesdesign** [comment]
> So I've done some quick testing.
> 
> Make a copy of the `index.html` file found in `/themes/terminal/layouts/_default/` that should be located in your `RootWebsiteFolder/layouts/_default` folder.
> 
> Locate the PageContext section and add the two lines below:
> 
> ```
> {{ $PageContext := . }}                                                     
>      {{ if .IsHome }}                                                       
>        {{ if not .IsHome }} <!-- ADD IN THIS LINE HERE                                                          
>          {{ $PageContext = .Site }}                                                
>     {{ end }}      <!-- ADD IN THIS LINE HERE                                                            
> {{ end }}   
> ```
> 
> After saving, this made my main page look like this:
> 
> ![screen](https://user-images.githubusercontent.com/15257477/197074430-54ef738f-3eb5-4a93-b26f-be4a8b323ddd.png)
> 
> And other pages that are not the home page will still show lists as intended:
> 
> ![screen1](https://user-images.githubusercontent.com/15257477/197082889-12588aa3-54c9-487d-81d2-d6f32e3e793f.png)
> 
> Instead of having the Updates as a post make it a folder in your `content/posts/` then move all of your actual posts into that folder and it will paginate them as intended.

I'll try this out today after my work day 😄 thank you!

**Comment by Umbragloom** [comment]
@Erioldoesdesign sounds good. hope this is what you were looking for. If anything comes up please let me know!

**Comment by Erioldoesdesign** [comment]
> Make a copy of the `index.html` file found in `/themes/terminal/layouts/_default/` that should be located in your `RootWebsiteFolder/layouts/_default` folder.

Does this index.html copy stay in the _default folder or go somewhere else?

**Comment by Erioldoesdesign** [comment]
I've been having trouble with getting the updates page to display the posts :/ i'll push to my sites repo so you might be able to take a look?
