### ISSUE TITLE
Error with yarn dev command and npm run build

### ISSUE THREAD

**Issue by gkuba** [panr/hugo-theme-terminal#377]
I was trying to add some color themes to this pack following your instructions on modifying files and #199 #200 but I am getting an error. 

```
yarn run v1.22.19
$ webpack --mode=development --watch
Browserslist: caniuse-lite is outdated. Please run:
  npx browserslist@latest --update-db
  Why you should do it regularly: https://github.com/browserslist/browserslist#browsers-data-updating
node:internal/crypto/hash:71
  this[kHandle] = new _Hash(algorithm, xofLen);
                  ^

Error: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:71:19)
    at Object.createHash (node:crypto:133:10)
    at BulkUpdateDecorator.hashFactory (/mnt/c/Projects/gkuba-site/themes/terminal/node_modules/webpack/lib/util/createHash.js:155:18)
    at BulkUpdateDecorator.digest (/mnt/c/Projects/gkuba-site/themes/terminal/node_modules/webpack/lib/util/createHash.js:80:21)
    at /mnt/c/Projects/gkuba-site/themes/terminal/node_modules/webpack/lib/DefinePlugin.js:595:38
    at _next32 (eval at create (/mnt/c/Projects/gkuba-site/themes/terminal/node_modules/tapable/lib/HookCodeFactory.js:19:10), <anonymous>:42:1)
    at _next10 (eval at create (/mnt/c/Projects/gkuba-site/themes/terminal/node_modules/tapable/lib/HookCodeFactory.js:19:10), <anonymous>:97:1)
    at Hook.eval [as call] (eval at create (/mnt/c/Projects/gkuba-site/themes/terminal/node_modules/tapable/lib/HookCodeFactory.js:19:10), <anonymous>:121:1)
    at Hook.CALL_DELEGATE [as _call] (/mnt/c/Projects/gkuba-site/themes/terminal/node_modules/tapable/lib/Hook.js:14:14)
    at Compiler.newCompilation (/mnt/c/Projects/gkuba-site/themes/terminal/node_modules/webpack/lib/Compiler.js:1053:26) {
  opensslErrorStack: [ 'error:03000086:digital envelope routines::initialization error' ],
  library: 'digital envelope routines',
  reason: 'unsupported',
  code: 'ERR_OSSL_EVP_UNSUPPORTED'
}

Node.js v18.10.0
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by panr** [comment]
I'm getting rid of Webpack, so this master branch will become obsolete soon. Instead, please use a code from this branch `https://github.com/panr/hugo-theme-terminal/tree/module` where you can do changes without compiling them with Webpack.

**Comment by gkuba** [comment]
Thanks I'll give that a try and get back to you

**Comment by gkuba** [comment]
I tried to install it via the module method and got the following error.

`WARN 2022/10/17 13:28:24 module "terminal" not found; either add it as a Hugo Module or store it in "/home/gkuba/gkuba/themes".: module does not exist
go: go.mod file not found in current directory or any parent directory.
        'go get' is no longer supported outside a module.
        To build and install a command, use 'go install' with a version,
        like 'go install example.com/cmd@latest'
        For more information, see https://golang.org/doc/go-get-install-deprecation
        or run 'go help get' or 'go help install'.
Error: failed to get ["-d" "github.com/panr/hugo-theme-terminal@module"]: failed to execute 'go [get -d github.com/panr/hugo-theme-terminal@module]': failed to execute binary "go" with args [get -d github.com/panr/hugo-theme-terminal@module]: go: go.mod file not found in current directory or any parent directory.
        'go get' is no longer supported outside a module.
        To build and install a command, use 'go install' with a version,
        like 'go install example.com/cmd@latest'
        For more information, see https://golang.org/doc/go-get-install-deprecation
        or run 'go help get' or 'go help install'.
 *errors.errorString`

**Comment by gkuba** [comment]
When I tried it with `hugo mod init github.com/panr/hugo-theme-terminal@module themes/terminal` I got this error 

```
hugo mod init github.com/panr/hugo-theme-terminal@module themes/terminal
WARN 2022/10/17 13:47:48 module "terminal" not found; either add it as a Hugo Module or store it in "/home/gkuba/gkuba/themes".: module does not exist
go: malformed module path "github.com/panr/hugo-theme-terminal@module": invalid char '@'
Error: failed to init modules: failed to execute 'go [mod init github.com/panr/hugo-theme-terminal@module]': failed to execute binary "go" with args [mod init github.com/panr/hugo-theme-terminal@module]: go: malformed module path "github.com/panr/hugo-theme-terminal@module": invalid char '@'
 *errors.errorString
```

**Comment by gkuba** [comment]
I wasn't able to get it installed with the `hugo mod` command but the git clone did work. 

Something to note though in your config.toml 
` # replacements = "github.com/panr/hugo-theme-terminal -> themes/terminal"`
Should actually be
` # replacements = "github.com/panr/hugo-theme-terminal -> terminal"`

or you will get the error:

```
Error: module "themes/terminal" not found; either add it as a Hugo Module or store it in "/home/gkuba/gkuba/themes".: module does not exist
Total in 54 ms
```

**Comment by panr** [comment]
Oh, I will look at this issue. AFAIR everything worked well when I submitted this new branch 🤔 

> I will say I LOVE how much easier it is to change to custom colors now tyvm!!

Right? :D That's why I will replace the branches soon ⏲️

**Comment by panr** [comment]
What will happen if you run this command `hugo mod init github.com/panr/hugo-theme-terminal@module` (without the directory path as you did the first time)

**Comment by panr** [comment]
OK, got it:

```.bash
hugo mod init github.com/panr/hugo-theme-terminal@module
hugo mod get -u
# or
hugo mod get github.com/panr/hugo-theme-terminal@module
```

then in config file:

```toml
[module]
  # this is needed when you fetch the theme as a submodule to your repo.
  # replacements = "github.com/panr/hugo-theme-terminal -> themes/terminal"
[[module.imports]]
  path = 'github.com/panr/hugo-theme-terminal'
```

and when I run `hugo server`, everything works.

**Comment by gkuba** [comment]
I ended up forking your repo making my color changes and then installing it as a submodule. 

So other than getting the initial setup working everything else works great. Its VERY easy to make theme changes now which I appreciate. 

Thanks again for checking into this.

**Comment by panr** [comment]
Cool, good to hear that! I will clean the whole theme up when I finally get some time for that 🙏
