### ISSUE TITLE
Different color per post

### ISSUE THREAD

**Issue by Nixo371** [panr/hugo-theme-terminal#380]
Is there a way to have different posts have a different color theme? I have read the part about configuring the config.toml file but that seems to change the whole site. I there a way to have one post be orange while another is pink?

**Comment by panr** [comment]
Just add `color = "[value]"` to the front matter.

**Comment by Nixo371** [comment]
Hi!
```
+++
title = "About"
date = "2022-10-24T10:07:08+02:00"
author = ""
authorTwitter = "" #do not include @
cover = ""
tags = ["", ""]
keywords = ["", ""]
description = ""
showFullContent = false
readingTime = false
hideComments = false
color = "[pink]"
+++
```
This is what I have, but the theme is still orange on my website, what am I doing wrong?

**Comment by panr** [comment]
You have remove the brackets, by `[ value ]` I meant `a value of a color`, so you need to set it like this `color = "pink"`

**Comment by Nixo371** [comment]
Haha sorry, I misunderstood. All working now, thanks!
