### ISSUE TITLE
[Bug] Error in .Lastmod.Format

### ISSUE THREAD

**Issue by hbourgeot** [panr/hugo-theme-terminal#381]
When in my ```config.toml``` file i put ```showLastUpdated = true```  hugo gives me this error:

<details> <summary>hugo server -D error output</summary>
<pre>
Change of config file detected, rebuilding site.
2022-10-24 06:37:16.872 -0400
ERROR 2022/10/24 06:37:16 render of "page" failed: "/home/henrry-go/Documentos/proyectos/estudiandev/themes/terminal/layouts/_default/single.html:11:74": execute of template failed: template: _default/single.html:11:74: executing "main" at <.Lastmod.Format>: can't evaluate field Lastmod in type time.Time
ERROR 2022/10/24 06:37:16 render of "page" failed: "/home/henrry-go/Documentos/proyectos/estudiandev/themes/terminal/layouts/_default/single.html:11:74": execute of template failed: template: _default/single.html:11:74: executing "main" at <.Lastmod.Format>: can't evaluate field Lastmod in type time.Time
ERROR 2022/10/24 06:37:16 render of "page" failed: "/home/henrry-go/Documentos/proyectos/estudiandev/themes/terminal/layouts/_default/single.html:11:74": execute of template failed: template: _default/single.html:11:74: executing "main" at <.Lastmod.Format>: can't evaluate field Lastmod in type time.Time
ERROR 2022/10/24 06:37:16 failed to render pages: render of "page" failed: "/home/henrry-go/Documentos/proyectos/estudiandev/themes/terminal/layouts/_default/single.html:11:74": execute of template failed: template: _default/single.html:11:74: executing "main" at <.Lastmod.Format>: can't evaluate field Lastmod in type time.Time
Rebuilt in 120 ms
</pre>
</details>

But when I put this option to false, rebuild normally

<details> <summary>My hugo config</summary>
<pre>
baseurl = "/"
languageCode = "es-es"
languageLang = "es"
copyright = "Henrry Bourgeot. Todos los derechos son reservados"
defaultContentLanguage = 'es'
title = "Un Blog de un Estudiante Dev"
theme = "terminal"

[params]
  \# dir name of your main content (default is `content/posts`).
  \# the list of set content will show up on your index page (baseurl).
  contentTypeName = "posts"

  \# ["orange", "blue", "red", "green", "pink"]
  themeColor = "blue"

  \# if you set this to 0, only submenu trigger will be visible
  showMenuItems = 3

  \# set theme to full screen width
  fullWidthTheme = false

  \# center theme with default width
  centerTheme = true

  \# if your resource directory contains an image called `cover.(jpg|png|webp)`,
  \# then the file will be used as a cover automatically.
  \# With this option you don't have to put the `cover` param in a front-matter.
  autoCover = true

  \# set post to show the last updated
  \# If you use git, you can set `enableGitInfo` to `true` and then post will automatically get the last updated
  showLastUpdated = true
  \# Provide a string as a prefix for the last update date. By default, it looks like this: 2020-xx-xx [Updated: 2020-xx-xx] :: Author
  updatedDatePrefix = "Actualizado"

  \# set all headings to their default size (depending on browser settings)
  \# oneHeadingSize = false # default

  \# whether to show a page's estimated reading time
  readingTime = true

  \# whether to show a table of contents
  \# can be overridden in a page's front-matter
  Toc = true

  \# set title for the table of contents
  \# can be overridden in a page's front-matter
  TocTitle = "En esta página"

[taxonomies]
  tag = "tags"
  category = "categories"

[languages]
    [languages.es]
        languageName = "Spanish"
        weight = 1
        owner = "Henrry Bourgeot"
        menuMore = "Mostrar más"
        readMore = "Leer más"
        readOtherPosts = "Leer otros posts"
        newerPosts = "Posts más recientes"
        olderPosts = "Posts más viejos"
        missingContentMessage = "Página no encontrada..."
        missingBackButtonLabel = "Volver a la página principal"
        categories = "Categorías"
    
        [languages.es.params.logo]
            logoText = "EstudianDev"
    
        [languages.es.menu]
            [[languages.es.menu.main]]
            identifier = "posts"
            name = "Posts"
            url = "/posts"
            [[languages.es.menu.main]]
            identifier = "tags"
            name = "Temas"
            url = "/tags"
         [[languages.es.menu.main]]
            identifier = "category"
            name = "Categorías"
            url = "/categories"

</pre>
</details>

**Comment by panr** [comment]
You have to add `enableGitInfo` prop as well as the comment says.

**Comment by hbourgeot** [comment]
> You have to add `enableGitInfo` prop as well as the comment says.

I enabled It after of make this issue and it still not working, in development environment and production environment fails.

**Comment by panr** [comment]
OK, I see the issue with my code. I'll fix it within few minutes.

**Comment by hbourgeot** [comment]
> OK, I see the issue with my code. I'll fix it within few minutes.

Many Thanks

**Comment by panr** [comment]
@hbourgeot can you pull the latest changes and try again?

**Comment by hbourgeot** [comment]
@panr Thanks you very much, it worked 😁. Now I'll close this issue.

**Comment by panr** [comment]
Glad to hear that! 🙌
