### ISSUE TITLE
Scss editing not seamless, may need compilation step

### ISSUE THREAD

**Issue by DreStation** [panr/hugo-theme-terminal#384]
Tested this on a new site with the theme added as a submodule.
Editing any of the .scss files in `themes/terminal/assets/css` shows no effect.

There's currently no npm script to recompile scss. Versions prior to 3.0 used webpack for that.
Furthermore, if you try running `npm i`, it will fail because there is a trailing comma in `package.json`, on line 38.

What I ultimately want to do is edit the colors in variables.scss.

Also, I want to say that this theme is amazing. I appreciate that this is still being updated with 3.0.

**Comment by panr** [comment]
Hmm... just tested it on a new setup and it works as intended. When I change something in `themes/terminal/assets/css/...` it also changes on the website. Like in `themes/terminal/assets/css/variables.scss` I changed `$color: white` to `$color: red` and the change appeared on the website while I was running `hugo server` in the background.

**Comment by panr** [comment]
>  if you try running npm i, it will fail because there is a trailing comma in package.json, on line 38.
Oh, didn't catch that. Just pushed the fix. Thanks!

**Comment by DreStation** [comment]
I have a feeling that the problem lies with how I setup the site. I noticed that changing `themeColor` in `config.toml` changes only the favicon and not the whole color scheme. I tried this with the theme as a submodule and when installed locally.

**Comment by panr** [comment]
And both ways still don't work?

**Comment by mpostument** [comment]
> I have a feeling that the problem lies with how I setup the site. I noticed that changing `themeColor` in `config.toml` changes only the favicon and not the whole color scheme. I tried this with the theme as a submodule and when installed locally.

For me themeColor is also ignored. Was fine before the latest updates. https://github.com/panr/hugo-theme-terminal/issues/385

**Comment by panr** [comment]
Do you have your website repos public? I'd like to look inside the project structure. Maybe there's something I missed during the rewrite 🤔

**Comment by DreStation** [comment]
https://github.com/DreStation/drestation.github.io
Something to note is that in `config.toml` I have to exclude the module params to be able to run `hugo server`

**Comment by panr** [comment]
> Something to note is that in config.toml I have to exclude the module params to be able to run hugo server

If you are using the theme as a submodule, you have to get rid of the module settings entirely from the config file. It would be safer to delete `[module]` tags as well.

I also spotted that you are overriding the new `footer.html` — https://github.com/panr/hugo-theme-terminal/blob/6601fd0b147c2d541aeb92a4cdba908be1d04f80/layouts/partials/footer.html — which now contains Hugo's built-in bundler to handle JS files.

Other than that, it looks OK imho.

**Comment by DreStation** [comment]
Removing all the `[module]` tags fixed it! Editing .scss files and changing themeColor is working.

![image](https://user-images.githubusercontent.com/93152029/198891794-331943e9-b6eb-426f-bf6f-8256fea0e72c.png)

And yeah, I didn't realize that the footer had been updated.

Closing this issue, thank you for your help!

**Comment by mpostument** [comment]
@panr here is link yo my repo https://github.com/mpostument/content-mpostument

**Comment by panr** [comment]
@mpostument I just cloned your repo and... it seems to be working just fine 🤔 

https://streamable.com/i584z6
