### ISSUE TITLE
tags not displayed in example.com/tags/

### ISSUE THREAD

**Issue by red0xff** [panr/hugo-theme-terminal#39]
If there are posts having a given tag, navigating to ``example.com/tags/<TAG>/`` yields all such posts.

However, when we navigate to ``example.com/tags/``, we are given a blank page.

Example: [https://mickie1.gitlab.io/blog/tags/](https://mickie1.gitlab.io/blog/tags/)

If I understand correctly, ``tags`` is one of the default [taxonomies](https://gohugo.io/content-management/taxonomies/), and the page at ``example.com/tags/`` should be updated automatically, why is it an empty page?

**Comment by panr** [comment]
Because I didn't provide an index page showing a list of all tags. My default `list.html` layout shows only posts ;-)
