### ISSUE TITLE
How do I add a panel like the one in Vercel example?

### ISSUE THREAD

**Issue by WendellAdriel** [panr/hugo-theme-terminal#398]
I want to add a panel like this one to some of my pages
![image](https://user-images.githubusercontent.com/11641518/204036073-c4150d80-62be-49c9-83ce-5aee1c3f10c6.png)

But I'm not finding how to do that in the theme or in the exampleSite
Does anyone know how I can do that?

**Comment by jiriks74** [comment]
I know how to do something simmilar [on my site](https://stfka.eu/)

<details>

<summary>Looks something like this</summary>

![Screenshot_2022-11-25-22-32-41-887-edit_org mozilla firefox](https://user-images.githubusercontent.com/54378412/204057206-06c39eb8-65df-4352-b8d6-ad0d53db13d6.jpg)

</details>

If you want to do this you need to create a table o one row and one column:

```md
| Hello there! |
| ------------ |
```

**Comment by WendellAdriel** [comment]
Oh that’s nice!
Thanks @jiriks74!!!

**Comment by panr** [comment]
https://github.com/panr/hugo-theme-terminal/issues/187
