### ISSUE TITLE
Options in language menu appears beside the header art

### ISSUE THREAD

**Issue by runitmisra** [panr/hugo-theme-terminal#400]
Hello, I am new to Hugo and still learning how stuff works. I copied over the example site contents folder and the config.toml to my site root directory, and I see this:
![image](https://user-images.githubusercontent.com/32189847/205422536-8fdb73ca-f0bf-4f6c-a94b-cfaaaa51116e.png)

There was no edit done to the config.toml (except changing the alignment to center, but with default alignment also I see the same issue)

Can someone help with this?

**Comment by panr** [comment]
You have to use Hugo **Extended** package instead of the default one.
