### ISSUE TITLE
Documentation on homepage header

### ISSUE THREAD

**Issue by Sir-Photch** [panr/hugo-theme-terminal#405]
I am wondering on how to add this kind of "Hello there..." homepage header with a border around it:

![grafik](https://user-images.githubusercontent.com/47949835/208936310-b2fa36b7-7e9c-4714-a529-ef160115ec59.png)

Is this `hugo-theme-terminal`-specific?

**Comment by panr** [comment]
Just wrote about it on the demo website. Hope this will help https://hugo-terminal.vercel.app/framed-box

**Comment by Sir-Photch** [comment]
Thank you very much!
