### ISSUE TITLE
Is it possible to change theme color on the fly with a button?

### ISSUE THREAD

**Issue by linuxgamingcentral** [panr/hugo-theme-terminal#406]
I want to add a link on my site where a person can change the theme color. So, say for example they wanted blue rather than the default red. Is it possible to change the string of `themeColor` in config.toml to do this? Website source code is available here: https://github.com/linuxgamingcentral/website

**Comment by panr** [comment]
It's not possible. The theme uses SCSS to compile all CSS files (containing color variables) during the build time. CSS variables are not exposed anywhere.
