### ISSUE TITLE
Please use v-prefixed tags

### ISSUE THREAD

**Issue by QuLogic** [panr/hugo-theme-terminal#407]
In Go modules, tag names must be in the form `v1.2.3`; the tags here are of the form `1.2.3`.

That means if you add as a submodule (with no version specifier), you get the latest _commit_ on `master`:
```
$ hugo mod get github.com/panr/hugo-theme-terminal
$ tail -1 go.mod
require github.com/panr/hugo-theme-terminal v0.0.0-20230102221952-20fc1079fa31 // indirect
```

whereas on a theme using the v-prefixed tag names, you get the latest _tag_:
```
$ hugo mod get https://github.com/victoriadrake/hugo-theme-introduction
$ tail -1 go.mod
require github.com/victoriadrake/hugo-theme-introduction v6.0.0+incompatible // indirect
```

**Comment by panr** [comment]
Oh, thanks for letting me know. Just changed them: https://github.com/panr/hugo-theme-terminal/tags

**Comment by QuLogic** [comment]
Thanks!

This is closer now, but it looks like the `go.mod` module path is not valid:
```
$ hugo mod get github.com/panr/hugo-theme-terminal
go: no module dependencies to download
go: downloading github.com/panr/hugo-theme-terminal v2.1.0+incompatible
go: added github.com/panr/hugo-theme-terminal v2.1.0+incompatible
hugo: collected modules in 1863 ms

$ tail -1 go.mod
require github.com/panr/hugo-theme-terminal v2.1.0+incompatible // indirect
```
and if going to the latest explicitly:
```
$ hugo mod get github.com/panr/hugo-theme-terminal@v3.1.0
go: github.com/panr/hugo-theme-terminal@v3.1.0: invalid version: module contains a go.mod file, so module path must match major version ("github.com/panr/hugo-theme-terminal/v3")
```

Might need to tag a new v3 version after modifying the module path.

**Comment by QuLogic** [comment]
Ugh, and I just realized that the theme I gave as an example didn't have a `go.mod`, so it was probably not the best example of a module-based theme.

**Comment by panr** [comment]
Dang... Now it should work with `/v3`. I'll keep this issue open just in case of any other problems :-(

**Comment by QuLogic** [comment]
Great, this is working better now:
```
$ hugo mod get github.com/panr/hugo-theme-terminal/v3
go: no module dependencies to download
go: added github.com/panr/hugo-theme-terminal v2.1.0+incompatible
hugo: collected modules in 703 ms
go: downloading github.com/panr/hugo-theme-terminal/v3 v3.1.2
go: added github.com/panr/hugo-theme-terminal/v3 v3.1.2
```

I'm not totally sure why it downloads both v2 and v3; perhaps because v2 was pre-module? I don't know if there's anything that could be done to hide it. The theme does appear to work even with both listed, so maybe it's not a big deal.

The only problem is that `hugo mod tidy` removes the /v3 line, but I'm on a slightly older version, so I'll need to test with newer Hugo in case it's a bug in Hugo Modules.

**Comment by QuLogic** [comment]
> This `v2.1.0+incompatibile` dependency should disappear when you update the `config.toml` module path with `/v3`:

D'oh, of course! I even grepped for other copies of the module path and must have glossed over it.

> This doesn't happen to me thinking I guess the update of `config.toml` should also solve this for you.

Yep, works fine now.
