### ISSUE TITLE
Incorrect name for archetype?

### ISSUE THREAD

**Issue by QuLogic** [panr/hugo-theme-terminal#42]
In the config example, it says:

>  ```
> # dir name of your blog content (default is `content/posts`)
> ```

and according to [hugo's archetype docs](https://gohugo.io/content-management/archetypes/), it will look in:
1.    `archetypes/posts.md`
1.    `archetypes/default.md`
1.    `themes/my-theme/archetypes/posts.md`
1.    `themes/my-theme/archetypes/default.md`

but the file in this repo is named `post.md`. Shouldn't it be named `posts.md`?

**Comment by panr** [comment]
It depends. The name could be anything you want. I have in my setup `content/post/..` and `archetype/post.md`. So when I want to create a new post from archetype I'll do it like this: `hugo new post/some-title.md`.

But you're right. Comment in the config file could be misleading. I'll fix that ;-)
