### ISSUE TITLE
Header is broken on subpages

### ISSUE THREAD

**Issue by glad-dev** [panr/hugo-theme-terminal#425]
A minimal working example of the bug can be found in [this repository](https://github.com/glad-dev/terminal-error).

The framed header is broken when using it in a subfolder.

`http://localhost:1313/posts/` displays the correct header:
![image](https://user-images.githubusercontent.com/38458082/215349868-dd4a8644-3f87-405f-8280-5e41cd0c9f41.png)

`http://localhost:1313/other/` displays the broken header:
![image](https://user-images.githubusercontent.com/38458082/215349885-873a717a-46c7-44c9-ad8e-4bcf3fcef2c3.png)

**Comment by Sir-Photch** [comment]
A workaround for this may be adding this to your `Config.toml`:
```toml
[markup.goldmark.renderer]
    unsafe = true # Allow HTML in md files
```
and this around the content of your `_index.md`:
```html
<div class="framed">
    content...
</div>
```
