### ISSUE TITLE
Syntax highlighting is broken for language `nix`

### ISSUE THREAD

**Issue by DavHau** [panr/hugo-theme-terminal#436]
Not sure why the theme doesn't just use hugo's builtin syntax highlighting which works well for nix.
The prism version used should actually support nix, but it didn't work for some reason

**Comment by cizordj** [comment]
@panr stated [here](https://github.com/panr/hugo-theme-terminal/issues/29#issuecomment-475982429) that hugo's builtin syntax doesn't match the color-scheme of the theme.

Maybe it's a good idea to put this answer on an FAQ.
