### ISSUE TITLE
Theme not applied to gists

### ISSUE THREAD

**Issue by Sir-Photch** [panr/hugo-theme-terminal#438]
Hi, when I add a gist from github to my website with the shortcode 
`{{< gist foo bar >}}`
it appears without css-styling.

You can see an example [here](https://sir-photch.xyz/posts/23-01-31-0/).

**Comment by arnobsanzam** [comment]
> > Hi, when I add a gist from github to my website with the shortcode `{{< gist foo bar >}}` it appears without css-styling.
> > You can see an example [here](https://sir-photch.xyz/posts/23-01-31-0/).
> 
> Hi, I am trying to publish in GitHub pages but the site doesn't seem to have any CSS. Do you have any idea how I can solve it?

Resolved. I just had to use Github Actions instead of Deploy from a branch.
