### ISSUE TITLE
Can't access images in deployed site

### ISSUE THREAD

**Issue by EmilyGraceSeville7cf** [panr/hugo-theme-terminal#441]
[Here](https://github.com/command-line-interface-pages/site.github.io) is my site, and [there](https://github.com/command-line-interface-pages/site.github.io/blob/904fe36c59727d279921784a98477cfb2f2be0a2/static/git.jpg) is an image. I use it [here](https://github.com/command-line-interface-pages/site.github.io/blob/904fe36c59727d279921784a98477cfb2f2be0a2/content/about.md?plain=1#L13). When I run `hugo server` everything looks fine:

![image](https://user-images.githubusercontent.com/42812113/223944657-8ea3b048-3421-478a-9267-23b7848206fc.png)

But after deployment I get just `git man` text instead of the actual image. I don't get where things go wrong to fix it.

I've asked about this issue on Hugo forum and [got](https://discourse.gohugo.io/t/image-is-not-displayed-after-site-deployment-while-shown-locally/43367/9?u=emilyseville7cfg) the answer:

> You’ll need to contact the theme author to fix the other stuff that’s broken.

**Comment by arnobsanzam** [comment]
Hi, can you please tell me how you embedded the image?

**Comment by EmilySeville7cfg** [comment]
I've put in [about/](https://github.com/command-line-interface-pages/site.github.io/tree/main/content/about) directory and referred to it like [this](https://github.com/command-line-interface-pages/site.github.io/blob/main/content/about/index.md?plain=1#L13).

Hugo bundles helped me to avoid this issue described in the original post, BTW.

**Comment by arnobsanzam** [comment]
Thank you so much, fixed the issue.

**Comment by EmilySeville7cfg** [comment]
@panr, can u mention commit which closed this issue? Thanks!

**Comment by panr** [comment]
Sorry, I thought the issue was fixed. But also this doesn't look like something related to the theme. I wanted to check it for myself, but the links you provided don't work for me (404).

**Comment by EmilySeville7cfg** [comment]
@panr, I've updated links, can u check my site to reproduce the issue?
