### ISSUE TITLE
Duplicated robots metatag

### ISSUE THREAD

**Issue by cizordj** [panr/hugo-theme-terminal#446]
If you disable robots' access while using this theme it produces two HTML meta tags with the same name “robots”.

Here is an example:
```markdown
---
title: "Hello World"
date: "2023-03-22"
draft: false
description: "Page description"
noindex: true
---

# Hello world
```

It produces the following HTML:
```html
. . .
<meta name="robots" content="noodp">
<meta name="robots" content="noindex">
. . .
```

Please make sure that only one tag is created.

**Comment by davidhedlund** [comment]
@panr

[I didn't know how to contact you so I'm posting here. Please be patient.]

Thank you very much for publishing https://linuxgamingcentral.com/posts/how-to-update-dualsense-firmware-on-linux/ ! I tried the guide in Ubuntu 22.04 but failed. What do you think about the idea of writing a guide specifically for Ubuntu 22.04?

I'm willing to assist you. I have VMs installed to make things easier.
