### ISSUE TITLE
How do I manage menu location?

### ISSUE THREAD

**Issue by czernobogBlog** [panr/hugo-theme-terminal#458]
Hi, I want to manage the location of menu in the theme. Only after adding two menu the third menu goes in to "Show more" I don't want this. I want the third menu beside the rest of the menu instead of it going to "Show More"

![Screenshot from 2023-04-25 10-58-35](https://user-images.githubusercontent.com/121787824/234183053-a9ccdc1e-4a27-416b-b4cb-f9a6cffa376d.png)

Here's my menu config, kindly let me know what changes I will have to do
```
  [languages.en.menu]
      [[languages.en.menu.main]]
        identifier = "about"
        name = "About"
        url = "/about"
      [[languages.en.menu.main]]
        identifier = "RSS"
        name = "RSS"
        url = "https://my-website/index.xml"
      [[languages.en.menu.main]]
        identifier = "donate"
        name = "Donate"
        url = "/donate"
```

**Comment by DreStation** [comment]
Now that you mention it, this isn't anywhere on the README.
Here's how to set a weight on each menu:
```
  [languages.en.menu]
      [[languages.en.menu.main]]
        identifier = "about"
        name = "About"
        url = "/about"
        weight = 10 # first place
      [[languages.en.menu.main]]
        identifier = "RSS"
        name = "RSS"
        url = "https://my-website/index.xml"
        weight = 20
      [[languages.en.menu.main]]
        identifier = "donate"
        name = "Donate"
        url = "/donate"
        weight = 30 # last place
```

I'm glad I could be of help :smile:. This is my first time helping in a GitHub issue.
