### ISSUE TITLE
"Read Other Posts" buttons not responsive

### ISSUE THREAD

**Issue by blakeashleyjr** [panr/hugo-theme-terminal#464]
The buttons that are generated in the "Read Other Posts" section at the bottom of a post are not properly responsive:

![image](https://user-images.githubusercontent.com/56891775/235722364-315706c8-7f71-4829-8fb5-6e1a6b1fc014.png)

I was able to correct the issue:

![image](https://user-images.githubusercontent.com/56891775/235722579-51d876aa-13e2-437b-baa6-9104b87b0663.png)

I did this by modifying the following code in pagination.scss, but there may be a better way to do it:

```
  @media($phone) {
    // flex: 1;
    width: 90%;
    }
```

I also made some other stylistic choices you may consider:

![image](https://user-images.githubusercontent.com/56891775/235722950-7fd765f9-f6f5-48b6-8ec7-5833ea7a3031.png)

```
  a {
    display: flex;
    justify-content: center;
    flex: 1;
    padding: 8px 16px;
    text-decoration: none;
    text-overflow: ellipsis;
    // the next line was preventing the text from wrapping and only providing a very short cut of the title on mobile.
    // white-space: nowrap;
    overflow: hidden;
  }

  &__text {
    text-overflow: ellipsis;
    overflow: hidden;
  }

  &.next .button__icon {
    display: flex; // new
    margin-left: 8px;
    align-items: center; // new
  }

  &.previous .button__icon {
    display: flex; // new
    margin-left: 8px;
    align-items: center; // new
  }
```

Let me know your thoughts, and I would be happy to create a PR if you like some or all of the changes.

**Comment by icy-comet** [comment]
I noticed the same issue wherein the navigation buttons do not adapt to the mobile width. This is what I did:

```diff
diff --git a/assets/css/pagination.scss b/assets/css/pagination.scss
index c65efcb..53d4266 100644
--- a/assets/css/pagination.scss
+++ b/assets/css/pagination.scss
@@ -57,7 +57,7 @@
   appearance: none;

   @media($phone) {
-    flex: 1;
+    flex-basis: 1;
   }

   a {
@@ -67,13 +67,11 @@
     padding: 8px 16px;
     text-decoration: none;
     text-overflow: ellipsis;
-    white-space: nowrap;
     overflow: hidden;
   }

   &__text {
     text-overflow: ellipsis;
-    white-space: nowrap;
     overflow: hidden;
   }
```

**Before Changes:**
![before changes image](https://user-images.githubusercontent.com/50461557/236609322-766099d6-39f1-4aec-aebb-898b0808d664.png)


**After Changes:**
![after changes image](https://user-images.githubusercontent.com/50461557/236609303-ce98d57c-233d-4daf-9da1-0ec369d3c4c4.png)

**Comment by blakeashleyjr** [comment]
@icy-comet Do you have an opinion on flex-basis vs width? Not an expert on CSS, so wanted to see if you had a reason for using flex-basis instead.

@panr Any thoughts?
