### ISSUE TITLE
Feature Request: Search Page

### ISSUE THREAD

**Issue by speatzle** [panr/hugo-theme-terminal#47]
Id like to have a searchbar on my site using your theme but i real bad at css/html stuff.
Coud you make a page in the template like mentioned [here](https://gist.github.com/sebz/efddfc8fdcb6b480f567).
thx -Sammy

**Comment by sophiabrandt** [comment]
With minimal effort, you can use the `extended_footer` to add a **Duckduckgo search feature**.
Create a new file `layouts/partials/extended_footer.html` with the following content:

```html
<div style="box-sizing: content-box; margin-left: auto; margin-right: auto; max-width: 60ch;">
    <form method="get" id="search" action="http://duckduckgo.com/">
      <input type="hidden" name="sites" value="YOURDOMAIN.COM"/>
      <input type="hidden" name="k8" value="#444444"/>
      <input type="hidden" name="k9" value="#D51920"/>
      <input type="hidden" name="kt" value="h"/>
      <input type="text" name="q" maxlength="255" placeholder="Search&hellip;"/>
      <input type="submit" value="DuckDuckGo Search" style="visibility: hidden;" />
    </form>
    <button style="margin: 0.5rem;" type="submit">Search</button>
</form>
</div>
```

Replace `YOURDOMAIN.COM` with your domain. You can adjust the HTML/CSS to your liking.

More info here: https://duckduckgo.com/search_box

**Comment by jimmyhess** [comment]
Implementing https://fusejs.io/ would be nice.
