### ISSUE TITLE
Security vunerability for package js-yaml; need upgrade

### ISSUE THREAD

**Issue by hrmnjt** [panr/hugo-theme-terminal#48]
Issue 1: Versions js-yaml prior to 3.13.0 are vulnerable to Denial of Service. By parsing a carefully-crafted YAML file, the node process stalls and may exhaust system resources leading to a Denial of Service.

Issue 2: Js-yaml prior to 3.13.1 are vulnerable to Code Injection. The load() function may execute arbitrary code injected through a malicious YAML file.

js-yaml package needs to be upgraded

**Comment by hrmnjt** [comment]
Screenshot for your reference:
![Screenshot from 2019-06-07 20-19-46](https://user-images.githubusercontent.com/10371494/59113124-18f4af80-8962-11e9-9cf4-ea625d7d8693.png)

**Comment by panr** [comment]
Yup. Fixed that already ;-)

**Comment by hrmnjt** [comment]
Thanks!
