### ISSUE TITLE
All section titles are in uppercase

### ISSUE THREAD

**Issue by hao-lee** [panr/hugo-theme-terminal#486]
I think the theme should keep the original case as in the md file.

**Comment by panr** [comment]
You can always delete this part of code from .css file ;-)

**Comment by hao-lee** [comment]
Sure... But it would be even better if we can config it in toml...

**Comment by hao-lee** [comment]
Your suggestion is certainly reasonable, but it would require users to modify the theme’s code directly to meet their needs. It seems like a better approach would be to allow users to create a new CSS file in their Hugo source directory, which could then override the theme’s default styles. Just an idea, though I’m not sure if this is feasible.

**Comment by panr** [comment]
> It seems like a better approach would be to allow users to create a new CSS file in their Hugo source directory, which could then override the theme’s default styles. Just an idea, though I’m not sure if this is feasible.

**Comment by panr** [comment]
>

**Comment by hao-lee** [comment]
Got it!
I tried this method. But it seems `style.css` is loaded as the last one so I have to use `!important` to override the previous style.

<img width="724" alt="图片" src="https://github.com/user-attachments/assets/d4b4af36-a6f4-4a81-9fd0-6ec2f3141d39">

**Comment by panr** [comment]
No you don't have to use `!important`, because **it's loaded as the last one** ;-) Just make sure you're overriding things using the same specificity (https://www.w3schools.com/css/css_specificity.asp) as in the default styles, this matters.

This code should revert headings to the default browser styles:

```css
h1, h2, h3, h4, h5, h6 {
  font-size: revert;
  text-transform: none;
}
```
