### ISSUE TITLE
ligature settings in body (main.css & terminal.css) can break other fonts

### ISSUE THREAD

**Issue by RogDolos** [panr/hugo-theme-terminal#489]
After adding another font, I was seeing some odd unexpected behaviour, due to these ligature settings for body{} in both terminal.css and main.css:
  font-feature-settings: "liga", "tnum", "zero", "ss01", "locl";
  font-variant-ligatures: contextual;

I recommend moving those lines into font.css specifically for the Fira Code font imports. That seems more appropriate and less likely to trigger fonts with cosmetic ligatures. IMHO alternate ligatures should be indicated per-font.

**Comment by panr** [comment]
Done, thanks!
