### ISSUE TITLE
How does one change the prism.js theme?

### ISSUE THREAD

**Issue by revsuine** [panr/hugo-theme-terminal#499]
Hi there, firstly thanks for making this theme; it looks beautiful.

I wanted to change the prism.js theme for code highlighting. I tried just putting my own `prism.css` in `assets/css/prism.css` in my site's directory (not in the theme directory) but that doesn't seem to have done anything.

I may be missing something obvious, but I'd appreciate being pointed in the right direction. Or if this is not something users can easily do, it would be a good feature to have where users can use their own `prism.css`.

**Comment by panr** [comment]
@revsuine you can do this easily:

1. replace `prism.css` as you did
2. remove `syntax.css` or comment its content out 

Restart the server ;-)

**Comment by revsuine** [comment]
I'm sorry but I'm still seeing the default prismjs theme. I tried using [this theme](https://github.com/PrismJS/prism-themes/blob/master/themes/prism-gruvbox-dark.css) by placing it in `assets/css/prism.css` and I also put an `assets/css/syntax.css` file which was just a comment, but no difference. I also tried editing the theme itself with those same changes and still the same.

**Comment by revsuine** [comment]
> I'm sorry but I'm still seeing the default prismjs theme. I tried using [this theme](https://github.com/PrismJS/prism-themes/blob/master/themes/prism-gruvbox-dark.css) by placing it in `assets/css/prism.css` and I also put an `assets/css/syntax.css` file which was just a comment, but no difference. I also tried editing the theme itself with those same changes and still the same.

Never mind, I tried in a fresh hugo site and it does work, so I'm going to try figure out what's wrong with my own hugo site where this doesn't work.

**Comment by revsuine** [comment]
> > I'm sorry but I'm still seeing the default prismjs theme. I tried using [this theme](https://github.com/PrismJS/prism-themes/blob/master/themes/prism-gruvbox-dark.css) by placing it in `assets/css/prism.css` and I also put an `assets/css/syntax.css` file which was just a comment, but no difference. I also tried editing the theme itself with those same changes and still the same.
> 
> Never mind, I tried in a fresh hugo site and it does work, so I'm going to try figure out what's wrong with my own hugo site where this doesn't work.

Figured it out—I'd written my own `footer.html` but left out the parts for prismjs :)

Thanks for the awesome theme!
