### ISSUE TITLE
[Feature Request] Icon shortcodes

### ISSUE THREAD

**Issue by Zhai2333** [panr/hugo-theme-terminal#50]
Add shortcode support to icons such as [Font Awesome](https://fontawesome.com), [Material Design Icons](https://materialdesignicons.com), etc.

**Comment by panr** [comment]
@Zhai2333 do you have any particular case for that?

**Comment by Zhai2333** [comment]
I was creating a _Contact_ page, and I need some brand icons instead of insert inline SVG / including a webfont myself.

A Example: [Zhai2333/hugo-shortcode-mdi](https://github.com/Zhai2333/hugo-shortcode-mdi/). But it's acting weird on non-HTML documents.

**Comment by panr** [comment]
This is the feature anyone could add easily on her/himself (adding a webfont, new shortcode — like this above, or inline svg...). I don't think the theme should have this built-in...

**Comment by Zhai2333** [comment]
That's okay! Thank you.
