### ISSUE TITLE
Menu only shows 2 entries and then "show more" if more than that

### ISSUE THREAD

**Issue by KatieTheDev** [panr/hugo-theme-terminal#502]
If I have 3+ entries, it only shows a "Show More" button after the first two, and the order is wrong as well. It seems to display alphabetically.

**Comment by roddie-digital** [comment]
Not sure of a way to change the ordering but you can increase the number displayed before adding a dropdown by editing the value for `showMenuItems` under `[[params]]` in `hugo.toml`.

**Comment by KatieTheDev** [comment]
Thank you. Does it still use default for mobile if I set that? Otherwise, is that a seperate setting I can force as well? As for order I just want a Home link to come first and don't particularly care about order after that.

**Comment by roddie-digital** [comment]
Hmm, if use mobile view in Firefox (<kbd>Ctrl</kbd>+<kbd>Shift</kbd>+<kbd>M</kbd>) it just collapses it all to a dropdown with the label "Menu"

**Comment by KatieTheDev** [comment]
Perfect. Will do. Closing.

**Comment by panr** [comment]
To order items in Hugo, you can use the `weight` param. Lower value == higher priority.

>  Lighter items float to the top, while heavier items sink to the bottom.

Ref: https://gohugo.io/methods/page/weight/

**Comment by KatieTheDev** [comment]
Thank you!! 
-------- Original Message --------On 11/22/24 00:42, Radek Kozieł  wrote:
To order items in Hugo, you can use the weight param. Lower value == higher priority.

Lighter items float to the top, while heavier items sink to the bottom.

Ref: https://gohugo.io/methods/page/weight/

—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you modified the open/close state.Message ID: ***@***.***>
[
{
***@***.***": "http://schema.org",
***@***.***": "EmailMessage",
"potentialAction": {
***@***.***": "ViewAction",
"target": "https://github.com/panr/hugo-theme-terminal/issues/502#issuecomment-2493076329",
"url": "https://github.com/panr/hugo-theme-terminal/issues/502#issuecomment-2493076329",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
***@***.***": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]
