### ISSUE TITLE
`showLastUpdated` not being respected in config

### ISSUE THREAD

**Issue by rexdotsh** [panr/hugo-theme-terminal#503]
hi, ever since the last commit at https://github.com/panr/hugo-theme-terminal/commit/c779a7083471f5f6f7036dfd60e9ff9a321600f9#diff-b2ff2a8d1f2a8a15c65288757c8b9acde7bec0ef491acb8048f1ddb61985cc41R10 even if `showLastUpdated` is specified as false in `hugo.toml`, it still shows up on the blog post.

an easy fix for this i found is to simply revert that exact line from `if .Lastmod` to `if $.Site.Params.showLastUpdated` which respects the `hugo.toml` config

**Comment by panr** [comment]
Oh, you are right. I missed it during the review :-( Fixing it...

**Comment by rexdotsh** [comment]
> @rexdotsh should be fixed already with [b09f47a](https://github.com/panr/hugo-theme-terminal/commit/b09f47aae7bc7f2fdeab523d15d2a8d217c4dad1), can you confirm?

yes, fixed now. thanks so much!

**Comment by panr** [comment]
No problem, and sorry about the bug... ;-(

**Comment by KatieTheDev** [comment]
Sorry about the bug! I wrote that code and I'm surprised I missed it in my own testing. My bad. Glad it got fixed.
