### ISSUE TITLE
Using hugo module does not show latest changes

### ISSUE THREAD

**Issue by KatieTheDev** [panr/hugo-theme-terminal#505]
If I use the theme as a hugo module it is not up-to-date. It is only updated if I use a git submodule.

**Comment by panr** [comment]
Yes, because I haven't updated the latest release with those changes yet. I'll do it today.

**Comment by KatieTheDev** [comment]
Thank you. Sorry to bother. 
-------- Original Message --------On 11/24/24 01:27, Radek Kozieł  wrote:
Yes, because I haven't updated the latest release with those changes yet. I'll do it today.

—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: ***@***.***>
[
{
***@***.***": "http://schema.org",
***@***.***": "EmailMessage",
"potentialAction": {
***@***.***": "ViewAction",
"target": "https://github.com/panr/hugo-theme-terminal/issues/505#issuecomment-2495870073",
"url": "https://github.com/panr/hugo-theme-terminal/issues/505#issuecomment-2495870073",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
***@***.***": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by panr** [comment]
@KatieTheDev done 👍

**Comment by KatieTheDev** [comment]
Thank you! 
-------- Original Message --------On 11/25/24 00:12, Radek Kozieł  wrote:
@KatieTheDev done 👍

—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you were mentioned.Message ID: ***@***.***>
[
{
***@***.***": "http://schema.org",
***@***.***": "EmailMessage",
"potentialAction": {
***@***.***": "ViewAction",
"target": "https://github.com/panr/hugo-theme-terminal/issues/505#issuecomment-2497038875",
"url": "https://github.com/panr/hugo-theme-terminal/issues/505#issuecomment-2497038875",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
***@***.***": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]
