### ISSUE TITLE
Cannot build with this theme

### ISSUE THREAD

**Issue by PorterRyan** [panr/hugo-theme-terminal#513]
Building with this theme returns the following error:

`ERROR deprecated: resources.ToCSS was deprecated in Hugo v0.128.0 and will be removed in Hugo 0.141.0. Use css.Sass instead.`

Here's the page for css.Sass: https://gohugo.io/functions/css/sass/

**Comment by PorterRyan** [comment]
Reverting to the 0.139.0 version of Hugo allows the site to build normally. The deprecation message is only a WARN in that version, but in 0.140.0 it is an ERROR.

resources.ToCSS will need to be replaced with css.Sass in order for the theme to remain usable with newer versions of Hugo.

**Comment by panr** [comment]
Thanks for reporting this! I'll take a look at it soon.

**Comment by panr** [comment]
@PorterRyan hey, are you sure you are using v4.x of the theme? I tried to find the reference to this issue, but just figured out that since v4.x there is no SASS...

**Comment by PorterRyan** [comment]
Aha, no I am using an older version of the theme. My fork readme is still showing the "this theme is no longer maintained" message. I will update it and see if that resolves the issue (it sounds like it should).

**Comment by PorterRyan** [comment]
Confirmed, updating to the latest version of the theme solves this issue.
