### ISSUE TITLE
Order of menu entries

### ISSUE THREAD

**Issue by pontius** [panr/hugo-theme-terminal#55]
Currently the entries in the main menu are sorted alphabetically.
Is there a way to sort the entries manually?

**Comment by panr** [comment]
Yes, use `weight` param in config file.

**Comment by Xevion** [comment]
Is it just me who thinks this feature felt a bit hidden? I struggled for a while to figure out how to get it to sort, and even tried the `weight` part, but it didn't work (`string` vs `int` perhaps?).

I think the default configuration file or example configuration should make sure of the weight feature for new Hugo developers like me. It did not feel obvious and googling didn't work until I found this Issue.

**Comment by AntoniosBarotsis** [comment]
@panr Same here. Would be nice to include even a commented out `weight = 1` below any of the menu entries. Everything else is very nicely explained.
