### ISSUE TITLE
Relative paths

### ISSUE THREAD

**Issue by NefixEstrada** [panr/hugo-theme-terminal#6]
If you set the Hugo paths to relative, the theme breaks (it can't load the assets correctly)

**Comment by panr** [comment]
Could you give me any examples?

**Comment by NefixEstrada** [comment]
https://ipfs.io/ipfs/QmasaDGTMNWjfEaiNxxuVTsrdhrWEuJBdfTDt3vpELpuu6/

**Comment by NefixEstrada** [comment]
```html
<link rel="canonical" href="../about/" />


<link rel="stylesheet" href="assets/style.css">

  <link rel="stylesheet" href="assets/green.css">
```

**Comment by panr** [comment]
Have you tried this 
https://gohugo.io/content-management/urls/#relative-urls ?

**Comment by NefixEstrada** [comment]
Yes, as you can see in the example I provided, I already use it (`<link rel="canonical" href="../about/" />`, but it doesn't seem to apply in the header. I changed the `absURL` in the header to `relURL` and it's working now. Not sure how it should really be though, since if I now want to use absolute paths the problem is going to still be the same

**Comment by panr** [comment]
> If you set the Hugo paths to relative, the theme breaks (it can't load the assets correctly)

I presume the theme assets break in `public` directory, right? This is how it works locally ¯\_(ツ)_/¯

**Comment by NefixEstrada** [comment]
Not sure if I understood you, but what I did is:

- Activate the relative urls
- Build the site with `hugo`
- Publish the `public` folder and see how it doesn't work

**Comment by panr** [comment]
Hmm... does your `baseUrl` look like `https://yourdomain.com/something/`? If so, the problem is, that Hugo looks for your assets on `https://yourdomain.com/something/assets/style.css` not `https://yourdomain.com/assets/style.css`. That's why I use `absURL` function to correct the path.

**Comment by NefixEstrada** [comment]
Since I'm using IPFS to serve the blog, my `baseURL` is empty

**Comment by NefixEstrada** [comment]
Here you can see the source:
https://gitlab.com/Nefix/marmota-blog/tree/04e8f1fc4351f4f8d1f880b96dfa77ada71f928e/public

**Comment by panr** [comment]
I haven't worked with IPFS yet. Right now I don't know how to make theme assets work also for this case... 😢 I use `absURL` because Hugo documentation recommends it for themes to deal with domain issues...

**Comment by NefixEstrada** [comment]
Can you access the Hugo configuration from inside the theme? Because if you can, a simple if could be used to decide whether use `absURL` or `relURL`

**Comment by NefixEstrada** [comment]
Can you access the Hugo configuration from inside the theme? Because if you can, a simple if could be used to decide whether use `absURL` or `relURL`

**Comment by panr** [comment]
I'm sorry that I left this issue open for so long. I'm very busy right now and I still have no idea how to make it work properly 😞

**Comment by NefixEstrada** [comment]
Hey! Sorry for the late answer. I made a quick patch by changing all the `absURL` to `relURL`, since my blog is always going to be served with relative urls. I neither have an idea on how to solve it! :disappointed:
