### ISSUE TITLE
Feature Request: Support keywords on individual posts

### ISSUE THREAD

**Issue by PrakharSrivastav** [panr/hugo-theme-terminal#67]
Right now the default keyword list for the site shows up on all the posts as well. I am not sure at the moment if there is a way for each post to have its own keyword list?

I would like to request this feature to override the default site keywords with keywords on the post.

**Comment by panr** [comment]
By keywords you mean `<meta name="keywords" content="" />`?

**Comment by PrakharSrivastav** [comment]
Hi,

Yes, that's right. Right now the keywords in the config.toml file is available on all the posts. I can manually add the HTML <meta/> tag to fix it, but it would be nice to have the theme support it on all the pages.

Example : https://www.prakharsrivastav.com/

Check the keyword on the home page and on individual posts.

Thanks.

**Comment by panr** [comment]
I'll fix it soon ;-)

**Comment by panr** [comment]
Done ;-) Now you can add keywords as a `keywords` array inside your front matter, like this:
`keywords: [hello, friend]`. Keep in mind that this works separately from `tags`, so if you need keywords, you have to define them ;-)

**Comment by panr** [comment]
Shit, sorry... I fixed it on the other theme (hello friend) 😂

**Comment by panr** [comment]
@PrakharSrivastav just fixed it! https://github.com/panr/hugo-theme-terminal/commit/24e901f4606a923592c3ff164e072c382af400df

**Comment by PrakharSrivastav** [comment]
Perfect!! Verified and it works. 
Thank you for the active support.
Closing the issue.
