### ISSUE TITLE
Fix v0.58 Warning (Waiting for confirm)

### ISSUE THREAD

**Issue by Zhai2333** [panr/hugo-theme-terminal#79]
On current version of theme execute `hugo` will print this warning message:

```plaintext
WARN In the next Hugo version (0.58.0) we will change how $home.Pages behaves. If you want to list all regular pages, replace .Pages or .Data.Pages with .Site.RegularPages in your home page template.
```

May cause bugs in next release of Hugo?

Waiting for confirm.

- [ ] Confirmed

**Comment by panr** [comment]
I think I've fixed it here https://github.com/panr/hugo-theme-terminal/commit/060587ba383a2f3c767062da27e44f10801f5736

So everything should be fine with 0.58 😬

**Comment by Zhai2333** [comment]
Oops I found my branch is outdated 🤣 Now merged!
Thanks!

**Comment by panr** [comment]
Phew... great! 😅
