### ISSUE TITLE
Feature Request: Disqus template!

### ISSUE THREAD

**Issue by miphilomath** [panr/hugo-theme-terminal#8]
Disqus is not available in the theme by default, as the hugo default disqus template is not working by setting "disqusShortname" in config.toml

It would be awesome if it could happen by default and user don't have to setup the partial template to get the disqus comment service working :)

**Comment by panr** [comment]
@miphilomath Totally right. I'll add it tonight ;-)

**Comment by miphilomath** [comment]
Thank you! Looking forward to your patch :)

Although, I added using partial template, but I am getting comment section on my about page :D

**Comment by panr** [comment]
@miphilomath You can now add any comment system you want ;-) https://github.com/panr/hugo-theme-terminal/commit/d005155fa5259de2e4a7c05a50d72a07713723d5

**Comment by kdpuvvadi** [comment]
Adding Disqus shortname and enabling partial comments is enabling comments
