### ISSUE TITLE
Displaying posts

### ISSUE THREAD

**Issue by Boarders** [panr/hugo-theme-terminal#85]
On the Pages section I don't seem to be able to display content. I have a `/posts/_index.html` which looks as follows:

```
---
title: "Posts"
data:
categories:
  - posts
draft: false
showFullContent : true
---
```
This doesn't however display a list of blog posts when I click on Posts in the menu. I am probably doing something silly, any ideas on what is going wrong?

**Comment by panr** [comment]
The index file should be a markdown file, not html —> `posts/_index.md`
