### ISSUE TITLE
Custom color in markdown

### ISSUE THREAD

**Issue by Boarders** [panr/hugo-theme-terminal#86]
Suppose I wished to use a custom color in  a particular section of markdown. What is the easiest way to do that?

I  could surround it with <font color=[myColour]? ... </font> but this means changing the colour involves changing every instance. Is there a way to change the style.css to allow this and if so what do I need to do?

**Comment by panr** [comment]
@Boarders I would create shortcode wrapper for .md file's content ;-)
https://gohugo.io/templates/shortcode-templates/
