### ISSUE TITLE
themes/terminal/layouts/_default/list.html:8: unexpected "=" in operand

### ISSUE THREAD

**Issue by akprajapati** [panr/hugo-theme-terminal#89]
ERROR 2019/10/12 16:04:05 Current theme does not support Hugo version 0.40.1. Minimum version required is 0.57
Building sites … ERROR 2019/10/12 16:04:06 Failed to add template "theme/_default/list.html" in path "/opt/hugo/site-one/themes/terminal/layouts/_default/list.html": template: /opt/hugo/site-one/themes/terminal/layouts/_default/list.html:8: unexpected "=" in operand
Total in 29 ms
Error: Error building site: logged 2 error(s)

**Comment by akprajapati** [comment]
![image](https://user-images.githubusercontent.com/17410704/66700068-31a71480-ed0a-11e9-9269-3d1691baaf13.png)

**Comment by akprajapati** [comment]
![image](https://user-images.githubusercontent.com/17410704/66700076-4c798900-ed0a-11e9-8313-035973129f0a.png)

**Comment by panr** [comment]
As error says - you need to update hugo version to at least 0.57 😎

**Comment by akprajapati** [comment]
Yeah, right. Thanks for pointing that out :)
