### ISSUE TITLE
Feature request: Newlines in quotes

### ISSUE THREAD

**Issue by seqizz** [panr/hugo-theme-terminal#94]
Hi and thanks for the theme, I am currently considering to switch and realized few gimmicks seems visually disturbing. One of this is newlines is removed from the block quotes, not sure if intentional, but:

```
> Test block with
New line
```

Should show like:

> Test block with
> New line

But seems like 

> Test block with New line

Preferably with single ' > ' character only in the beginning, not sure which would be better though..

**Comment by jpanther** [comment]
The Markdown convention for a line break inside a paragraph is to place two spaces at the end of the previous line. If you adjust your code to the below, you should get the output you're looking for...

```
# note the two spaces after 'with' below

> Test block with  
New line
```

**Comment by seqizz** [comment]
Well.. that's a weird convention I didn't know.
Works flawlessly.. Thanks :no_mouth:
