### ISSUE TITLE
Separate pages for separate types/folders?

### ISSUE THREAD

**Issue by seqizz** [panr/hugo-theme-terminal#97]
Hi again,

My current theme only shows posts in the `content/post` directory on the homepage, all others are in their own menu (yet all of them has "type: post").

I guess some stuff changed on later hugo versions, sorry if I am over-confused over a simple issue :slightly_smiling_face: But can I achieve some result with terminal theme, without breaking the compatibility with theme upstream?

Basically:

```
content
|-section1
|-section2
|...
```

I'd like to see only posts from`section1` on homepage, and have a menu element named `section2` to reach the list of section2 posts. Either via some menu magic or setting different types to different sections?

If I understand correctly, this is related with #23 and #36

**Comment by panr** [comment]
@seqizz Sorry for a late response. I'm really busy right now with work related stuff ;-(

Anyway... I think you can do this without breaking anything. You can copy `list.html` from my theme, and create inside your site root `layouts/section2.html` (the file is copied version of list.html, just with changed name) and replace every `$.Site.Params.contentTypeName` in that file with `$.Site.Params.myOtherSection` (`myOtherSection` is a placeholder here!).

Then you can add `myOtherSection = "section2"` below `contentTypeName = "post"` (which targets `section1` in your example).

And in `section2` add `index.md` with proper front matter, eg:

```
+++
title = "This is my second section"
layout = "section2"
url = "/section2"
+++
```

And with these, you should be able to have `https://localhost:1313/section2` path with list of your posts inside `section2` dir.

I hope this will work, because I wrote this from my memory 😬

**Comment by seqizz** [comment]
Thanks for the explanation. While I've managed to create another type and put an index, the new type didn't appear here. Then I realized what I am trying to do and it dawned on me that I've completely described the issue wrong :man_facepalming:  Even the title is misleading..

The content is separated by directories and their respective links opens the related content well enough, even with default settings.

The issue is, homepage has all the content it can find with type = "post" currently. This was not the case with other themes I've used. 

Currently what I have is:
```
/content (root content folder, going to homepage only shows posts 1 and 2)
|--post1.md
|--post2.md
|--personal/ (directory, also linked via menu, going to /personal only shows posts 3 and 4)
        |-post3.md
        |-post4.md
|--technical/ (directory, also linked via menu, going to /technical only shows posts 5 and 6)
        |-post5.md
        |-post6.md
```

What terminal produces:
```
/content (root content folder, going to homepage shows ALL posts, 1 to 6)
|--post1.md
|--post2.md
|--personal/ (directory, also linked via menu, going to /personal only shows posts 3 and 4)
        |-post3.md
        |-post4.md
|--technical/ (directory, also linked via menu, going to /technical only shows posts 5 and 6)
        |-post5.md
        |-post6.md
```

I hope this time I am less drunk to explain, what I need from homepage to show only posts 1 and 2.

Thanks again :)

**Comment by panr** [comment]
Oh, I see... I just realized that I f*cked up with my "defaults", so yeah... I already have a major fix / change to that. New settings will be more flexible, but it can break so many sites 🤔 

I will push changes to another branch.

**Comment by panr** [comment]
@seqizz done — https://github.com/panr/hugo-theme-terminal/tree/multiple-content-types#multiple-content-types

I still need to work on README, but you can test it right now. Just to pull changes and switch to `multiple-content-types` branch and let me know if it works. 

Also if you have any idea how to improve README after these changes, let me know as well 👍

**Comment by seqizz** [comment]
Thanks :tada: 

(This was why I was trying not to break upstream compatibility, since it's not uncommon for a new theme version "break" the website. For example whoever copied a list.html will have a harder time for this branch I think :see_no_evil: )

New branch working great, now I can only display `type: post` on my homepage after setting other folders as different types and urls.

Two slightly disturbing issues I've seen, not sure if related so please ping if I should open a new issue for those (if yes please close the issue and thanks again) :

- tags seems not working, they're displayed on the post listing correctly, but once I click a tag (the `website.com/tags/exampletag` link), it shows no posts
- short posts does not show any preview on the homepage, not sure if intended

**Comment by panr** [comment]
> tags seems not working, they're displayed on the post listing correctly, but once I click a tag (the website.com/tags/exampletag link), it shows no posts

Fixed https://github.com/panr/hugo-theme-terminal/commit/65ec26da81f401a416bb3311f31babd9df288ef1

> short posts does not show any preview on the homepage, not sure if intended

For short posts use `description` prop in front matter.

**Comment by seqizz** [comment]
![image](https://user-images.githubusercontent.com/307899/68619788-6aced200-04cc-11ea-9a6d-b0c07d954cc7.png)

Thanks, closing.
